### ISSUE TITLE
SIGABRT on g++ with v2.0.0-develop.3. Version v1.10.0 works ok.

### ISSUE THREAD

**Issue by mgr-inz-rafal** [philsquared/Catch#1012]
## Description
I recently replaced Catch v1.10.0 with v2.0.0-develop.3.
Everything works correctly on Windows with Visual Studio 2017.

When I compile with:
"g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609"
I receive SIGABRT during one of the tests.

All tests are executed in the same way. I load some data from file, process it during two different algorithms that are expected to give the same result and finally I just compare two results.

Testing code is available here:
https://github.com/mgr-inz-rafal/tubac/blob/19ad88854278e2e27ab0bfe9ceb9c7cb78ed06ca/tests/src/tests.cpp#L308

### Steps to reproduce
Actually, I just run the tests with 
CHECK(result.first == result.second)
where result is defined as:
std::pair<std::string, std::string> result;

### Extra information
In the "old" version I have proper PASSED:
```
/home/prezes/Git/tubac/tests/src/tests.cpp:333: 
PASSED:
  CHECK( result.first == result.second )
with expansion:
  "122
  12
  
  72"
  ==
  "122
  12
  
  72"
with messages:
  10 PRINT 1;2;
  20 PRINT 2
  30 PRINT 1;
  40 PRINT 2
  50 PRINT
  60 PRINT 7;2
  suites/print/semicolon.txt

```

In new version I have the following output:
```
/home/prezes/Git/tubac/tests/src/tests.cpp:333: 
PASSED:
  CHECK( result.first == result.second )
with expansion:
  "122
tubac_tests: /home/prezes/Git/tubac/tests/src/../../external/catch/catch.hpp:3723: std::__cxx11::string Catch::clara::TextFlow::Column::iterator::operator*() const: Assertion `m_pos < m_end' failed.
  12/home/prezes/Git/tubac/tests/src/tests.cpp:322: FAILED:
  {Unknown expression after the reported line}
due to a fatal error condition:
  10 PRINT 1;2;
  20 PRINT 2
  30 PRINT 1;
  40 PRINT 2
  50 PRINT
  60 PRINT 7;2
  suites/print/semicolon.txt
  SIGABRT - Abort (abnormal termination) signal

```

**Comment by philsquared** [comment]
Thanks for bringing this up. It's a pretty fundamental bug in the TextFlow library, which Clara (the arg parser lib) uses! So I've fixed it there (and added tests to catch that case), and propagated the fix to Clara and Catch2!
Although I've committed the fix it's not in the single include yet. However the change is trivial, so you may want to try it yourself. Just go the line that's asserting in Catch (3723) and change the condition there to:

```assert( m_pos <= m_end );```

(i.e. just make it `<=` instead of `<`). That's all it was! An over-eager assertion.
Most of my time looking at this was just spent mentally verifying that that was actually the right thing to do!

**Comment by mgr-inz-rafal** [comment]
Works as expected now, thanks for quick reply!
