### ISSUE TITLE
Align Listeners with common xUnit pratices

### ISSUE THREAD

**Issue by ruipacheco** [philsquared/Catch#1018]
I believe we should review Listeners. Most unit testing frameworks have special methods to be called before a test starts and after a test ends, commonly known as `setUp()` and `tearDown()`. 

Catch provides the same functionality but in the form of Listeners that can only be written in the main file and that use a different syntax than normal test code: tests have `TEST_CASE`, `SECTION` and `REQUIRE`; listeners are normal classes. Also and definitely not least, each Listener requires you to match which test is running before it can execute anything specific to that test.

I propose we replace the current Listener infrastructure with Fixtures similar to what purest provides:

> fixtures have explicit names and are activated by declaring their use from test functions, modules, classes or whole projects.

https://docs.pytest.org/en/latest/fixture.html#fixtures

C++ best practices encourage code to be split by files and namespaces by folders and doing the same  that pytest does would bring Catch in line with those practices.  If this cannot be done another good idea would be `setUp` and `tearDown` per file, per `TEST_CASE` and per `SECTION`. Since Catch supports nested `SECTION`s, public code created in the setup of a `SECTION` should be visible to all other `SECTION`s.

C++ tends to be used with large codebases and as things are the main file becomes confusing very quickly.

This issue is to keep a promise I made [here](https://github.com/philsquared/Catch/issues/986).

**Comment by philsquared** [comment]
"Catch provides the same functionality but in the form of Listeners"
- that's not quite accurate.
By which I mean: you *could* use Listeners for that - but that's not what they for - and is certainly not the best way to do it.

Instead "setup" and "teardown" is accomplished in a much more natural (for C++) way!
You just use `SECTION`s within a `TEST_CASE`, and each `SECTION` will be like a test case in a framework with fixtures. You can then do your setup and teardown (although, typically, less need for the latter in C++) outside the `SECTION`s.

If you're prefer the more XUnit style of fixtures, you can still do that, too (see https://github.com/philsquared/Catch/blob/master/docs/test-fixtures.md)

**Comment by ruipacheco** [comment]
> You just use SECTIONs within a TEST_CASE, and each SECTION will be like a test case in a framework with fixtures. You can then do your setup and teardown (although, typically, less need for the latter in C++) outside the SECTIONs.

How is this achieved? So any code I call before and after a section is executed as setup/teardown?

> If you prefer the more XUnit style of fixtures [...]

I'm sure I'm missing something but how would you make a fixture fire on setup/teardown?

**Comment by ruipacheco** [comment]
> By which I mean: you could use Listeners for that - but that's not what they're for - and is certainly not the best way to do it.

I remember discussing Fixtures with you and I always had in mind setup/teardown. What should they be used for then?

**Comment by philsquared** [comment]
If we've discussed this before, I apologise. I don't remember that discussion at present (anything else that might jog my memory?). I suspect we're talking a little cross purposes here somewhere - let's try to identify where.

When you talk about Fixtures I'm thinking of a style of unit testing where you have a test *class*, which has a set of test *methods*. The class has `setup()` and `teardown()` methods and/ or constructor and destructor - either way they are called before and after calling each test method, respectively (with a new instance created for each test). And this is what I was referring to when I said that Catch does support this style of testing (with brief documentation at the link I supplied). Is this different to what you were thinking of?

However, as I've said, that's not the most idiomatic way to achieve a similar result with Catch. In C++ we're used to using stack-based RAII objects to do before/ after operations and this more naturally fits the idea of `SECTION`s. So, yes, as you say, "any code I call before and after a section is executed as setup/teardown". In fact the "as setup/teardown" is redundant in this sentence. The whole point of this is to get us away from having to think of setup/ teardown as special things that happen at special times. It's just code that gets used like any other code. The setup/teardown effect is achieved simply by code outside the `SECTION`s being called before and/ or after the code within. Each `SECTION` at the same level is executed by re-executing the test case from the start - so you get the same level of isolation you do with Fixtures. But `SECTION`s go further because you can nest them - and so have multiple levels of setup/teardown (see the `vector` example in the tutorial - https://github.com/philsquared/Catch/blob/master/docs/tutorial.md#test-cases-and-sections).

Is any of this still unclear? Am I still missing what you're asking for?

**Comment by horenmar** [comment]
>How is this achieved? So any code I call before and after a section is executed as setup/teardown?

Yes, that is the entire point of `SECTION`s
```cpp
TEST_CASE("foo") {
    std::cout << "setup\n";
    SECTION("bar") {
        std::cout << "bar\n";
    }
    SECTION("baz") {
        std::cout << "baz\n";
    }
    std::cout << "tear down\n";
}
```
will have output of
```
setup
bar
tear down
setup
baz
tear down
```

The same logic applies over arbitrarily nested `SECTION`s\*

As for listeners, seeing listeners as a way to implement set-up, tear-down is a bit misguided. They can be used that way, sure, but that only makes sense if you have some global state that needs to be cleared/reset with some granularity (these can range from logging singleton, where you presumably want to drop stored logs if everything is OK, to a hardware device that needs restart signal).

You can also use methods of objects as your test cases, in which case the setup/tear down is in constructor/destructor and are run before each test case method is called.


\* However, having parallel deeply nested sections tends to make following the test logic a bit hard.

**Comment by ruipacheco** [comment]
@philsquared I was thinking of [this issue](https://github.com/philsquared/Catch/issues/851) I opened where you say I should use Listeners. Listeners are great but they're limited to the main() file and that will get confusing very quickly, at least to me.

I may have misread what you said but I'll try to use TEST_CASEs for now.

**Comment by horenmar** [comment]
@ruipacheco [Catch 2 listeners are no longer limited to main file.](https://github.com/philsquared/Catch/blob/catch2/docs/event-listeners.md#implementing-a-listener) This won't be backported to Catch Classic, however.

I still think that listener usage should be quite rare though, as they imply a common set of steps that need to be run before each assertion/section/test case/test run. Given how test case + sections already enable reusing common steps for certain set of assertions, this likely also implies a global state.


*(And global state is the enemy of unit testing)*

**Comment by ruipacheco** [comment]
I'm happy closing this issue.

**Comment by philsquared** [comment]
Thanks for linking the issue. Of course I remember that one now! :-)
But in there I was suggesting the use of Listeners for cross-cutting, environmental, setup/teardown (you mentioned starting/ stopping/ clearing databases etc), which you might want to do for all tests (either once at the start/ end, or before/ after every test case). In that case Listeners allows you to put that logic in one place.
But if you have to start making that logic conditional on which test is being run, then I don't think Listeners are the right solution - and `SECTION`s (or class based fixtures, if you prefer) are a better fit as we've discussed.

So I hope that clarifies things and you get it all working as cleanly as you would like.

**Comment by ruipacheco** [comment]
This is perfect, thanks!
