### ISSUE TITLE
ParseAndAddCatchTests not adding new tests without rebuilding the CMake cache

### ISSUE THREAD

**Issue by mmha** [philsquared/Catch#1035]
## Description
The CTest Integration does not scan for new tests in modified files after the CMake cache has been generated.

### Steps to reproduce

1.  `add_executable()` a test runner, `ParseAndAddCatchTests()` the target
2. Run CMake, build the tests, run them with CTest (works as expected)
3. Add a new test to the executable, rebuild the test runner
4. CTest does not run the new test

### Extra information

* Catch version: 2.0 (f972732)
* Operating System: Arch Linux
* CMake 3.9

**Comment by dvirtz** [comment]
I made a PR with a fix. Notice however that CMake will rerun on **every** change to test files so it might become a little annoyance.

**Comment by horenmar** [comment]
@dvirtz That also means that the entire compilation will run from scratch, correct?

**Comment by dvirtz** [comment]
No, CMake is smart enough to see that the cache hasn't changed, only CTest
configuration files.

On 12 Oct 2017 6:24 p.m., "Martin Hořeňovský" <notifications@github.com>
wrote:

@dvirtz <https://github.com/dvirtz> That also means that the entire
compilation will run from scratch, correct?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/philsquared/Catch/issues/1035#issuecomment-336172265>,
or mute the thread

**Comment by horenmar** [comment]
@dvirtz Good.
