### ISSUE TITLE
Unexpected Memory Cleanup

### ISSUE THREAD

**Issue by mrmcmuffinz** [philsquared/Catch#1045]
## Description
I was trying out Catch and wrote some tests cases to test out some basic linked list theory code I wrote. During the execution of said test cases I found it out that one of my tests were failing so I tried to investigate it thinking I wrote some problematic code. It turns out that when one section completes and goes to execute another one a memory structure I allocated using the new keyword some how gets assigned to NULL. The way I validated this was not my code was to create a getter on my class and compare it to nullptr between sections and sure enough on the next section it was set to NULL.

```shell
(gdb) run
Starting program: /Users/abe/scratch/cpp/single_linked_list/tester.app
[New Thread 0x1a03 of process 19662]
warning: unhandled dyld version (15)

Thread 2 hit Breakpoint 7, ::____C_A_T_C_H____T_E_S_T__ () at tester.cpp:22
22	        REQUIRE( intLinkedList->getHead() != nullptr );
(gdb) p intLinkedList->getHead()
$11 = (IntElement *) 0x100400730
(gdb) c
Continuing.

Thread 2 hit Breakpoint 6, ::____C_A_T_C_H____T_E_S_T__ () at tester.cpp:25
25	        REQUIRE( intLinkedList->getHead() != nullptr );
(gdb) p intLinkedList->getHead()
$12 = (IntElement *) 0x0
(gdb) l tester.cpp:22
17	        REQUIRE( intLinkedList->size() == 2 );
18	        intLinkedList->insert(10);
19	        REQUIRE( intLinkedList->size() == 3 );
20	        intLinkedList->insert(1);
21	        REQUIRE( intLinkedList->size() == 4 );
22	        REQUIRE( intLinkedList->getHead() != nullptr );
23	    }
24	    SECTION( "Should be able to find inserted elements in list." ) {
25	        REQUIRE( intLinkedList->getHead() != nullptr );
26	        REQUIRE( intLinkedList->find(10) == true );
(gdb) quit
A debugging session is active.

	Inferior 1 [process 19662] will be killed.

Quit anyway? (y or n) y
```

### Steps to reproduce

In the tar you will the a build script that will compile and execute the test. Note, I did try running valgrind on this but I'm just picking up C++ again so it is kinda out of my league right now to determine the proper issue. I have a suspicion the issue is around `Section::~Section()` but I have nothing to prove it. Valgrinds output is in `memcheck.output` and the command I used to run it was `valgrind --leak-check=yes --leak-check=full --show-leak-kinds=all -v --track-origins=yes --log-file="memcheck.output" ./tester.app`

[code.tar.gz](https://github.com/philsquared/Catch/files/1377718/code.tar.gz)

### Extra information

* Catch version: **v1.10.0, Generated: 2017-08-26 15:16:46.676990**
* Operating System: **macOS Sierra, Darwin \<redacted\>.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64**
* Compiler+version: **clang++**
```shell
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
* valgrind: `valgrind-3.13.0`

**Comment by philsquared** [comment]
I think the key point you are missing here is that each section is executed independently of the others.
That is, on the first run through the test case will be entered, then the first section ("list should be of size 0"). But after coming out of that section _the subsequent sections are skipped!_
The test case is then executed again, this time skipping the _first_ section. The second section is entered (where all the values are inserted), then the rest of the sections are skipped.
The test case is executed again, skipping the first two sections and going into the third. The tests in here will fail because we're working with a new list - not the one that was populated previously.
This process continues until, only on the final run through, does it go into the section, "cleaning up the list", which deletes it. All the other lists leaked.

If you want one section to follow on from another (e.g. the finds to operate on the same list as the inserts) you'll need to _nest_ sections.

To fix deletion you should move that out of sections (just at the end of the test case) - but I would advise holding the list in a `scoped_ptr` (if it really needs to be heap allocated) - or better still as a value on the stack - that way you don't rely on execution actually reaching the delete - it will happen even if the function has an early exit (e.g. due to an exception).

Here's a modified version with that advice applied:

```c++
TEST_CASE( "Single Linked List", "[a]" ) {
    IntLinkedList intLinkedList;
    SECTION( "list should be of size 0" ) {
        REQUIRE( intLinkedList.size() == 0 );
    }
    SECTION( "List should not contain element with value 1" ) {
        REQUIRE( intLinkedList.find(1) == false );
    }
    SECTION( "List should be able to insert element, find it and validate size." ) {
        intLinkedList.insert(1000);
        REQUIRE( intLinkedList.size() == 1 );
        intLinkedList.insert(100);
        REQUIRE( intLinkedList.size() == 2 );
        intLinkedList.insert(10);
        REQUIRE( intLinkedList.size() == 3 );
        intLinkedList.insert(1);
        REQUIRE( intLinkedList.size() == 4 );
        REQUIRE( intLinkedList.getHead() != nullptr );

        SECTION( "Should be able to find inserted elements in list." ) {
            REQUIRE( intLinkedList.getHead() != nullptr );
            REQUIRE( intLinkedList.find(10) == true );
            REQUIRE( intLinkedList.find(1) == true );
            REQUIRE( intLinkedList.find(100) == true );
            REQUIRE( intLinkedList.find(1000) == true );
            REQUIRE( intLinkedList.getHead() != nullptr );

            SECTION( "Removing element should set size accordingly and not be able to find it." ) {
                REQUIRE( intLinkedList.remove(1) == true );
                REQUIRE( intLinkedList.remove(100) == true );
                REQUIRE( intLinkedList.remove(10) == true );
                REQUIRE( intLinkedList.size() == 0 );
                REQUIRE( intLinkedList.find(1) == false );
            }
        }
    }
}
```

Note that this still has issues in `remove` and in the destructor of the list, so still fails as written - but the flow through Catch is now correct. I'll leave the other fixes to you (or ping us on the #learn channel on the cpplang Slack :-) ).

**Comment by martinmoene** [comment]
FYI: Section are described in the Tutorial, section [Test cases and sections](https://github.com/philsquared/Catch/blob/master/docs/tutorial.md#test-cases-and-sections), "not so much" in the [reference](https://github.com/philsquared/Catch/blob/master/docs/test-cases-and-sections.md#test-cases-and-sections).

**Comment by mrmcmuffinz** [comment]
@philsquared thanks for responding so quickly and I appreciate the feedback. That being said I wouldn't be surprised if my linked list implementation has a few dozen bugs here or there I'm just trying repick up my C++ skills. I will go over the recommended way of writing the tests and see if that correlates with the documentation @martinmoene pointed out. I do have to confess I did find the documentation and just looked predominately at the source examples instead of reading it end to end, that will be another thing on my todo list. To conclude is this behavior you described @philsquared  in the documentation @martinmoene pointed out? If so then I think we can just close this as user error.

**Comment by philsquared** [comment]
Yes, in fact the tutorial docs that @martinmoene pointed to uses an example I wrote for testing `std::vector` - so there is actually some similarity with what you're trying to do (I use that as an example of where nested sections are useful). For it to really make sense, though, you do need read the bit after the first example that explains the sequence of events when discovering sections.

They're straightforward enough once you know how they work - but it can be a little less obvious when you first encounter them.

I'll close this for now - but if you have any further issues please re-open, or raise a new ticket. Or we can chat on cpplang for general advice.
