### ISSUE TITLE
Add REQUIRE_TIME

### ISSUE THREAD

**Issue by egorpugin** [philsquared/Catch#1056]
## Description
Does catch have something like `REQUIRE_TIME( expr, time );`?
It will be very useful in some concurrency/parallel tests.

If `expr` is executed under `time`, test is ok, otherwise failed.

### Extra information
My simple implementation:
```
template <typename F, typename ... Args>
auto get_time(F &&f, Args && ... args)
{
    using namespace std::chrono;

    auto t0 = high_resolution_clock::now();
    std::forward<F>(f)(std::forward<Args>(args)...);
    auto t1 = high_resolution_clock::now();
    return t1 - t0;
}

#define REQUIRE_TIME(e, t)                 \
    if (get_time([&] { REQUIRE(e); }) > t) \
        REQUIRE_NOTHROW(throw std::runtime_error("time exceed on " ## #e))
```

**Comment by philsquared** [comment]
The short answer is: no.
I am adding micro-benchmarking support (on the Catch2 branch) which might help in the long run - although that's more for surfacing timings, rather than asserting on them.

The reason I'm not sure if asserting on run-time is a good idea is that it becomes non-deterministic, and can lead to flickery tests. Sometimes that's unavoidable (in which case I'd at least hide them from the default run with `[.]` or similar, so only run them deliberately).

So I don't think I'd want this to be built in to Catch, but your implementation seems like it should do the job (although I'm not sure it needs to be implemented in terms of a lambda - perhaps just have `REQUIRE_TIME` open a scope and do the timer inline around the `REQUIRE` directly?)

**Comment by egorpugin** [comment]
I see, thanks! Closing this.

> perhaps just have REQUIRE_TIME open a scope and do the timer inline around the REQUIRE directly?

Sure, just reusing my get_time function in example.
