### ISSUE TITLE
New feature: use multiple reporters

### ISSUE THREAD

**Issue by wichert** [philsquared/Catch#169]
I would like to be able to use both the standard reporter and the junit reporter at the same time. I think my use cases is a common one: I want human readable output on stdout so the emails jenkins sends me are useful, but I want the junit XML output for tracking purposes.

Looking at other test runners I use they handle this by always reporting to stdout while an XML output option creates one or more XML files in junit format in addition to the normal stdout output.

**Comment by michaelbprice** [comment]
@philsquared, we are working on a tool that allows people to more easily migrate between test frameworks without having to rewrite a whole bunch of existing test code.  Having the ability to have multiple reporters registered during a single call to `Session::run` would be incredibly valuable.

It looks like this issue is quite old at this point.  If there were a pull request that implemented this feature (we almost hacked one up that worked around the framework limitation), would you consider it for inclusion?

**Comment by philsquared** [comment]
Catch does actually now support multiple reporters

**Comment by Reonaydo** [comment]
> Catch does actually now support multiple reporters
How it can be used? How can I set write "junit" into file and "console" to stdout ?

**Comment by philsquared** [comment]
I was probably a bit premature in announcing that.
Technically Catch *does* support multiple reporters - but not in any useful way yet. Or rather it supports them for the purpose of [Listeners](https://github.com/philsquared/Catch/blob/master/docs/event-listeners.md). As a side effect you can *specify* multiple reporters, but there is currently no way to specify different locations for them to write to - so they all go either to the console or to the same file. Like I said, not useful.
It shouldn't be a huge job to address that but it's just not been high enough priority yet.
Hopefully will get to it at some point.

**Comment by LesserBabka** [comment]
I would also appreciate this functionality (to be useful).

**Comment by fbradyirl** [comment]
It would be great to see this implemented.

**Comment by cjw296** [comment]
Would still be great to see this, or are there other solutions (nested reported or some such?)

**Comment by Viatorus** [comment]
@philsquared  Can we please reopen this issues?

**Comment by horenmar** [comment]
@Viatorus #1712
