### ISSUE TITLE
SECTION execution regression

### ISSUE THREAD

**Issue by stefanholek** [philsquared/Catch#191]
Given this test:

``` cpp
TEST_CASE("catch/siblingSections", "")
{
    printf("0");
    SECTION("s1", "") {
        printf("1");
    }
    SECTION("s2", "") {
        printf("2");
    }
    SECTION("s3", "") {
        printf("3");
    }
    printf("\n");
}
```

Pre-1.0 the output used to be:

  01
  02
  03

With current tip the test prints instead:

  0
  01
  02
  03

More curiously, given this test:

``` cpp
TEST_CASE("catch/nestedSections", "")
{
    printf("0");
    SECTION("s1", "") {
        printf("1");
        SECTION("s2", "") {
            printf("2");
            SECTION("s3", "") {
                printf("3");
            }
        }
    }
    printf("\n");
}
```

Pre-1.0 the output used to be:

  0123

While with current tip the test prints:

  0
  01
  012
  0123

**Comment by philsquared** [comment]
Prompted by #552 I had a look through this issue again.
I can't remember exactly when it went in now, but I did managed to change the behaviour back to the pre-1.0 ordering (and more recently tightened it up even more with another section-tracking overhaul).
For anyone still watching this issue who had problems before could you confirm (or otherwise) whether recent versions still have any issues for you?

**Comment by ruderik1** [comment]
Just started using catch 1.5.1 today for integration tests, and immediately stumbled upon this issue.
When comparing my tests to the OP, the output is;
01
02
03
When all sections PASS
When section3 fails, the output is
01
02
03
0
(newline is not very visible, but present ;)
So the whole testcase is executed again after the failing section, which is not needed and takes a lot of extra time.

**Comment by philsquared** [comment]
Hi @ruderik1,
Unfortunately this is unavoidable.
Catch needs to execute the code in order to discover the sections. When everything passes it comes out of section 3, notices there are no more sections to discover, and so completes.
But in the failing case it doesn't know if there were still more sections to discover so it needs to do one more run through to be sure. Possibly in the case it could be made to work (if it knows there are no more sections that it has skipped on previous run-throughs) but that doesn't generalise. For example: consider what happens if section 1 throws. It has never even seen section 2, so the only way it can discover it is to run through again, skipping section 1.

**Comment by ruderik1** [comment]
Hi Phil,
Thanks for the explanation. I didn't realize that the sections are dynamically discovered, is there a reason for that ('cause they are statically defined, i would assume dynamic discovery is not needed)?
I like the concept of catch, and specially the ease of use. I'm going to try if i can use setup/teardown instead of code in the testcase which then hopefully doesn't get executed when there is no section to execute anymore.
Thanks,
Ruud

**Comment by philsquared** [comment]
Since nobody else (other than @ruudsieb) chimed in on this thread in the intervening couple of years I'm going to assume that there are no outstanding issues?
I'm marking this for closure unless anyone objects in the next few days.

**Comment by bkuhns** [comment]
Looks good to me, I just tried out the following test:

``` C++
TEST_CASE("A SECTION should be run on the first pass.")
{
	auto sectionRun = false;
	SECTION("If this section runs, then the test should always succeed.") {
		sectionRun = true;
	}
	REQUIRE(sectionRun);
}
```

And the test passes, implying it runs through the section on the first run.

**Comment by philsquared** [comment]
Cool - thanks @bkuhns
