### ISSUE TITLE
Show in which test an assertion fails

### ISSUE THREAD

**Issue by gnzlbg** [philsquared/Catch#219]
When an internal assertion fails (`assert()` from <cassert>) the test terminates but Catch doesn't show in which section the assertion failed making these things really hard to debug. The test name is not enough.

Note: I think the same happens if `std::terminate` is called. It would be really useful to know in which section of which test the program terminated.

**Comment by horenmar** [comment]
Since we have recently merged a signal rework, I decided to test this issue.

Given this source code against single-include `catch.hpp` generated from current master,
```cpp
#define CATCH_CONFIG_MAIN
#include "catch.hpp"

#include <cassert>
#include <exception>

TEST_CASE("TEST-terminate", "[.term]"){
    SECTION("First") {
        std::terminate();
    }
}

TEST_CASE("TEST-assert", "[.ass]") {
    SECTION("First"){
        assert(false && "Hello");
    }
}
```
ran like this ` ./a.out -s -r compact [.ass]`, I get this output
```
a.out: test.cpp:15: void ____C_A_T_C_H____T_E_S_T____3(): Assertion `false && "Hello"' failed.
test.cpp:14: failed: fatal error condition with message: 'SIGABRT - Abort (abnormal termination) signal'
Failed 1 test case, failed 1 assertion.

Aborted (core dumped)
```
which shows failure at line 14, which is the line of "First" section macro.

If I run the code like this `./a.out -s -r compact [.term]`, I get this:
```
terminate called without an active exception
test.cpp:8: failed: fatal error condition with message: 'SIGABRT - Abort (abnormal termination) signal'
Failed 1 test case, failed 1 assertion.

Aborted (core dumped)
```
which also shows the failure at the correct section.


Seeing this, I am inclined to close this issue.

**Comment by gnzlbg** [comment]
> Seeing this, I am inclined to close this issue.

What I actually had in mind (a long long time ago) was a bit more complex. Given:

```c++
#define CATCH_CONFIG_MAIN
#include "catch.hpp"

#include <cassert>
#include <exception>

void term() { std::terminate(); }
void assert_fail() {  assert(false && "Hello"); }

TEST_CASE("TEST-terminate", "[.term]"){
    SECTION("First") {
        term();
    }
}

TEST_CASE("TEST-assert", "[.ass]") {
    SECTION("First"){
        assert_fail();
    }
}
```

does the error message point me to `term/assert_fail` or does it point me to `SECTION("First")` as well? 

The motivation would be e.g. testing `std::vector`. Suppose `operator[]` does bound checking with assert. Arguably, `operator[]` might be used in a lots of test and sections, and when the assert triggers, one sees that something is indexing out of bounds. It would be nice if Catch could somehow pinpoint which test that came from. 

Running a debugger will show the back-trace, so I would not say this is high priority. But if Catch would tell me which test the assertion was triggered from, I think that information would save me from having to run a debugger at all in a lot of situations.

**Comment by horenmar** [comment]
@gnzlbg Your example still prints the line of the failing section, that is either line 11 or 17.


As to the other two issues, runtime speed of Catch has significantly improved even since last release. As far as compile time is concerned, I might try to measure it as well. There are ways to improve it, but the tradeoffs for Catch 1 are probably not worth it right now (maybe when there is only ~10 open issues and we have too much free time :smile:), but for Catch 2, keeping compile times down is one of the design goals. By the way, did you feel the compile times were too slow even with the test main separated?


As far as the second issue is concerned (tests in separated processes), that is a big one and the support is not likely to materialize anytime soon -- supporting Linux is not easy and supporting Windows is... pretty hard actually, but overall we would be willing to add support behind an opt-in macro.

**Comment by gnzlbg** [comment]
> Your example still prints the line of the failing section, that is either line 11 or 17.

I think we can close this issue then :) 

> By the way, did you feel the compile times were too slow even with the test main separated?

I think I did not tried that. I ported a bunch of GTest files (each with its own main) to Catch back then (when Catch was more or less released, this was a long time ago), and basically went from instant compiles to ~10-30s per file which hit my edit-compile-test cycle hard :/ 

> but for Catch 2, keeping compile times down is one of the design goals.

I will give it a try it when its released :)

> As far as the second issue is concerned (tests in separated processes), that is a big one and the support is not likely to materialize anytime soon

IIRC the original issue had some pointers to some implementations (probably the GTest one). For some reason I have in mind that it was around 1kLOC (or ~2kLOC) so it might not be such a big issue, but last time I checked that was a very long time ago.

**Comment by horenmar** [comment]
> I think I did not tried that. I ported a bunch of GTest files (each with its own main) to Catch back then (when Catch was more or less released, this was a long time ago), and basically went from instant compiles to ~10-30s per file which hit my edit-compile-test cycle hard :/

Yeah, Catch main compiles for ~5 seconds or more on weaker PCs, thats why the documentation suggests separate file for the main (standard test files compile and link against the main reasonably quickly).


Well, I am going to close this issue and leave the other one open for now.
