### ISSUE TITLE
testing private class members?

### ISSUE THREAD

**Issue by cseed** [philsquared/Catch#258]
Is there a best practice for accessing private members in test cases?  I didn't see anything in the documentation.  One option is to use:
`#define private public`

in the test case file, but that doesn't seem ideal.  I'm happy to use a friend declaration, but I don't see how to refer to the test case.

**Comment by DanielRamosAcosta** [comment]
Hi guys, my approach to this was define the following in my common header file:

    #ifdef __TEST__
    	#define private public
    #endif

And in my test target I added the `__TEST__` directive. Clean and easy.

Personally, If it were easy and uncomplicated I would prefer to have this integrated within the framework.
I recommend adding this to the tutorial.

**Comment by nabijaczleweli** [comment]
This is horribly UB and *will* fail horribly somewhere down the line

**Comment by DanielRamosAcosta** [comment]
Hummm you are right :cry:... ¿Any other solution?

**Comment by nabijaczleweli** [comment]
Yes: [do *not* test class internals](http://stackoverflow.com/questions/105007/should-i-test-private-methods-or-only-public-ones).

**Comment by DanielRamosAcosta** [comment]
wontfix and close then :smile:

**Comment by philsquared** [comment]
In a bizarre twist of fate I have just been bitten by `#define public private`!
It's in a set of tests testing some legacy code. The tests were added years ago but needed to reach into one of the objects to inspect some internal state. The object is implemented in a DLL (this is Windows).

Anyway, I just added another header file to the test file and it started giving linker errors.
Much head-scratching later I discovered that the accessibility of the exported functions was impacting their mangled names so the linker wasn't matching them up!

I think this is the the flip-side of ODR (the problem was multiple definitions mapping to the same implementation, rather than vice-versa). Either way nasty stuff.

To my shame I've fixed it to move the header file around for now (and added a comment!). But I do need to go back and address that properly. It's really not a good situation to be in!

**Comment by horenmar** [comment]
For anyone reading this later on, on Windows the visibility of members in an object also affects their layout. This can only bite you if you have mix of private and public member variables, but still.

DO NOT DO `#define public private`.

**Comment by philburr** [comment]
I _generally_ think it is best to unit test your _interface_.  However, I do disagree that one should _never_ test internals.  One should always be very careful about testing internal details because internal details can change and it makes your unit tests fragile and prone to maintenance.  However, there are cases that in my code I've found that are useful to unit test.  For example, I'm currently working on a class that is very math heavy and I need to be very careful that even internal functions do the right thing.  I will do unit tests on them initially to validate behavior and will probably eventually remove them (the unit tests) once I validate the implementation.

Anyway to answer the original question, what I do is put the testable code in a class in an unnamed namespace (I do almost all class implementation in headers), have the ultimate implementation derive from that class (either protectedly or privately as needed).  Then you have an implementation to test and an interface to test.  You can then easily consolidate when you've reached code maturity.

**Comment by ant6n** [comment]
When writing complicated algorithms, they will be split up into multiple methods, which will be composed in order to provide the final interface. It's valuable to test the components individually (that's why it is called "unit" testing). Not allowing tests on private methods will thus reduce coverage and make it more likely that bugs are not caught.

So far the only option seems to be to make the (individually testable) components of a complicated algorithm public, even though these should not be exposed in an interface. That's unfortunate.

The original question from 2014 was not really addressed in this thread. I'm a bit confused why the issue was closed.

**Comment by DanielRamosAcosta** [comment]
I think this issue isn't related to Catch2 in particular, is a more generic testing question, that could be asked as: How do I test class internals (private or protected methods)? Well, basically, you don't.

You shuld test those methods through the public API. If there is code that you can't reach, probably that code shouldn't be there.

If you need to test a specific private method that is complex enough, maybe that "complex enough" means that you have to [separate responsabilities in that class](https://en.wikipedia.org/wiki/Single-responsibility_principle).

But in the end, the tests should be flexible so you can change their internals without changeing the external API, that's another reason why you shouldn't test private methods.

**Comment by leonardopsantos** [comment]
> When writing complicated algorithms, they will be split up into multiple methods, which will be composed in order to provide the final interface. It's valuable to test the components individually (that's why it is called "unit" testing). Not allowing tests on private methods will thus reduce coverage and make it more likely that bugs are not caught.

Absolutely. I want to test _all_ methods of my classes (mainly because TDD). Maintaining my tests is _my_ problem, I'll be the one deciding if testing protected methods is a burden or not. The rule should be "you always want to test your public interface", not "you want to only test the public interface". Any code is only as good as its tests.

I see several solutions here:

1. Have a way for Catch2 to define test classes like [Google Test](https://google.github.io/googletest/advanced.html#testing-private-code) that can be friended in the class under test.
2. Use a delegate class, so the method you want to test is public there. You'll need to define the delegate on a separate, internal header that's only included in the source file if you want to keep it private.
3. Have two versions of your code, a production one and a test one. Have the test one use `-fno-access-control`. This is pretty awful, but it's oh so, so convenient.

My preferred approach is the third one: it's non-intrusive for the code under test, it's not a hassle like the second one.

For the fist one, you could do:

```c++

// Forward declaration of a fixture to test private members
struct TestFooPrivateMemberFixture;

class Foo {
    // Make the test fixture a friend to access private members
    friend TestFooPrivateMemberFixture;

private:
    int private_member = 42;

    void set(int v) {
        private_member = v;
    }

public:
    Foo(int value) : private_member(value) {}
    int get() const {
        return private_member;
    }
};

struct TestFooPrivateMemberFixture {
    // Delegate method to call the private method
    void callSet(Foo& foo, int value) {
        foo.set(value);
    }
};

// TEST_CASE_METHOD inherits from the fixture, but because friendship is not inherited,
// we need to define a delegate method in the parent class.
TEST_CASE_METHOD(TestFooPrivateMemberFixture, "Test Foo") {
    auto f = Foo(10);
    REQUIRE(f.get() == 10);
    callSet(f, 20);
    REQUIRE(f.get() == 20);
}
```

**Comment by neel** [comment]
If some method is private but it needs to be tested, I either move it to utils or in details and then add unit tests for it.
