### ISSUE TITLE
Are OR statements possible?

### ISSUE THREAD

**Issue by inequity** [philsquared/Catch#341]
Sorry to be dropping so many 'issues' here lately, but the google group is not super active.

I'm wondering if this type of statement is possible, because it seems like a logical thing that somebody would do:
`CHECK( (a == 1) || (a == 2) )`

I know that it won't compile like that. 'Statement too complex'... Is there a preferred method for doing this? It seems like a fairly common operation.

**Comment by tavianator** [comment]
Another thing is that when `||` or `&&` are overloaded, they stop short-circuiting.  So something like this:

```c++
CHECK(p == nullptr || !p->flag);
```

wouldn't be safe.  Better to keep it as-is IMO.

**Comment by horenmar** [comment]
I improved the documentation regarding asserts and now I am going to close this (actually I hoped github would autoclose this issue, but apparently the detection does not support list of commits :smile:).

**Comment by davids91** [comment]
I know the issue is closed, just wanted to add, that currently in the [docs/assertions](https://github.com/catchorg/Catch2/blob/master/docs/assertions.md#natural-expressions) it is stated that the workaround for the OR expressions is to simply put them into an additional parentheses. That is a lot more convenient, than any mentioned workaround, it's really effortless tbh. 

Just wanted to add this for anybody trying to google this problem ( like I did ) and finding this issue, instead of reading the docs thoroughly :innocent:
