### ISSUE TITLE
Old-style cast used in catch_timer.hpp on Windows

### ISSUE THREAD

**Issue by hostilefork** [philsquared/Catch#369]
Hello, trying Catch out in a project for the first time.  Seems to be working well!

There are a couple issues we hit due to having lots of warnings turned on.  We turned off a couple for the tests, like "missing default case in switch" and "duplicate definitions".  _(I think the default switch case one is a good warning personally...)_

But going through all the build platforms I hit one about old-style casts here:

https://github.com/philsquared/Catch/blob/master/include/internal/catch_timer.hpp#L30

It seems there was a commit related to removing them, that actually touched this file:

https://github.com/philsquared/Catch/commit/a31f05fe83197c2cf8fc529b96e595a3dc21b416

But maybe the Windows-conditional ones were overlooked?

**Comment by philsquared** [comment]
Thanks for bringing this up!
I've changed those casts to reinterpret_cast now on my local branch (will get pushed shortly).

As for the "missing fault case in switch" that one's more tricky. GCC and Clang give me warnings if I *include* the default case (they prefer me to exhaustively cover all enum cases). So I can't please both warnings at once. Since I have the GCC/ Clang ones keeping me honest (i.e. making sure I'm always fully specified) I'll leave it that way around.
