### ISSUE TITLE
Failure to link - clang++-3.7

### ISSUE THREAD

**Issue by dirvine** [philsquared/Catch#375]
Compile even the simple example produces this output. Ok in every other compiler

CMakeFiles/check_quad.dir/check_quad.cc.o: In function `Catch::TagParser::~TagParser()':
/home/dirvine/Devel/wwww/src/test/check_quad.cc:(.text+0x4846): undefined reference to `operator delete(void*, unsigned long)'
CMakeFiles/check_quad.dir/check_quad.cc.o: In function `Catch::TagExtracter::~TagExtracter()':
/home/dirvine/Devel/wwww/src/test/check_quad.cc:(.text+0x4910): undefined reference to `operator delete(void*, unsigned long)'
CMakeFiles/check_quad.dir/check_quad.cc.o: In function `Catch::TagExpressionParser::~TagExpressionParser()':
/home/dirvine/Devel/wwww/src/test/check_quad.cc:(.text+0x4fc9): undefined reference to `operator delete(void*, unsigned long)'
CMakeFiles/check_quad.dir/check_quad.cc.o: In function `Catch::LegacyReporterAdapter::~LegacyReporterAdapter()':
/home/dirvine/Devel/wwww/src/test/check_quad.cc:(.text+0x664e): undefined reference to `operator delete(void*, unsigned long)'
CMakeFiles/check_quad.dir/check_quad.cc.o: In function `Catch::NonCopyable::~NonCopyable()':
/home/dirvine/Devel/wwww/src/test/check_quad.cc:(.text+0x7506): undefined reference to `operator delete(void*, unsigned long)'
CMakeFiles/check_quad.dir/check_quad.cc.o:/home/dirvine/Devel/wwww/src/test/check_quad.cc:(.text+0x7516): more undefined references to `operator delete(void*, unsigned long)' follow
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by rioderelfte** [comment]
The link error is not caused by a problem in Catch but by a recent change in clang (see commits [229241](http://llvm.org/viewvc/llvm-project?view=revision&revision=229241) and [229597](http://llvm.org/viewvc/llvm-project?view=revision&revision=229597)). If you want to use clang-3.7 in C++14 mode you either have to update your standard library or compile your code using the `-fdefine-sized-deallocation` flag.

This is also mentioned on the [C++ status page](http://clang.llvm.org/cxx_status.html#n3778) of clang.

**Comment by dirvine** [comment]
A thanks for that. I will close this now, thanks for the update, very much appreciated.
