### ISSUE TITLE
Create stable release

### ISSUE THREAD

**Issue by vinipsmaker** [philsquared/Catch#385]
Is there a stable release/tag?

**Comment by HaMster21** [comment]
:+1: for adding it

At the moment the master seems not to build correctly for my project when it did before. Referencing a tag as a dependency would make this much less of a probelm.

**Comment by philsquared** [comment]
Rather than tagging I've been doing dev/ integration on the develop branch and merging back as a "release".
Either way it suffers from the problem that the people who experience the problems tend to be the ones who wait for the "stable release", so problems don't get picked up until then. I usually try and leave it quiet for some time before merging to mitigate this as much as possible.
Perhaps using tags instead would result in more people on the bleeding edge by default - while still allowing the more conservative to use a tagged release? I might experiment with that next time around.

@HaMster21 - are you still seeing issues with master? I don't recall seeing any other issue tickets raised by you for it? If it's still not working for you it would be great if you can raise an issue here.

**Comment by HaMster21** [comment]
@philsquared I'm sorry, but I was mixing up your project with [FakeIt](https://github.com/eranpeer/FakeIt) which was the build error root cause. Catch still works fine, thank you for your work :+1: 

As of the tagging of releases: I think that the convention *master is always stable* is fine, but still I think that tagged releases would be of help. I don't really like my builds including changed dependencies unnoticed, and I wouldn't be able to select a version of catch (i.e. for including it as version tag for the cmake module) as of now (pointing to a specific commit is bad practice :wink: ). Besides, GitHub makes it pretty easy to spot a new release in a starred project. And a Changelog is provided there as well.

**Comment by DavidEGrayson** [comment]
The README.md file is currently directing people to to the "develop" branch to download "the latest, single header, version" so I thought you were using the "develop" branch for releases.  After reading this thread I now think that is wrong.  It would be nice if the README could make it clear exactly what is experimental/bleeding and what is a stable release.  I also think using git tags, [semantic versioning 2.0.0](http://semver.org/), and maintaining a change log in the repository is the best practice.

I go into more detail about this in a discussion I started on the Google Group:
[Comprehensible versioning for Catch](https://groups.google.com/forum/#!topic/catch-forum/Z03uq5ujRgQ)

Here are some related issues on GitHub as well:
https://github.com/philsquared/Catch/issues/447
https://github.com/philsquared/Catch/issues/430
https://github.com/philsquared/Catch/issues/197

**Comment by philsquared** [comment]
Catch is now using Semantic Versioning and tagging
