### ISSUE TITLE
Extend CHECK_THROWS to allow checks on exception object

### ISSUE THREAD

**Issue by vadz** [philsquared/Catch#394]
It would be nice if it were possible to not only add that an exception of the specific type was thrown, but that it carries information about the expected error. E.g. check that its `what()` method returns the expected string or a custom exception class has the expected error code.

**Comment by cinemast** [comment]
Hi!

I would also very much appreciate such a feature. I am currently migrating a project from Boost-Test to Catch. This is the only feature I really miss in Catch.

**Comment by DavidEGrayson** [comment]
In the meantime, I think something like this should work:

~~~~
bool thrown = false;
try
{
  do_something_that_throws_an_exception();
}
catch(const myexception & e)
{
  REQUIRE(std::string(e.what()) == "something");
  thrown = true;
}
REQUIRE(thrown);
~~~~

**Comment by cinemast** [comment]
I've created a macro for myself, that looks very similar:

```cpp
#define CHECK_EXCEPTION_TYPE(throwCode, exceptionType, expression) {bool thrown = false; try {throwCode;} catch(exceptionType &ex) { CHECK(expression(ex)); thrown = true; } CHECK(thrown);}
```

It can than be used as the following:

```cpp
bool check_exception3(JsonRpcException const&ex)
{
    return ex.GetCode() == Errors::ERROR_RPC_INVALID_REQUEST && ex.GetData().size() == 2;
}

CHECK_EXCEPTION_TYPE(client.CallMethod("abcd", Json::nullValue), JsonRpcException, check_exception3);
```

**Comment by philsquared** [comment]
I'll confess I tend to use something similar to @DavidEGrayson's example:
```
try
{
  do_something_that_throws_an_exception();
  FAIL( "expected exception" );
}
catch(const myexception & e)
{
  REQUIRE(std::string(e.what()) == "something");
}
```

... which at least doesn't have to track the "thrown" state.
But, yes, I agree this really needs first class support in Catch - especially since Catch already has a general way of extracting the message from an exception object (more general than .what()) - so you should be able to assert on the exception message without even needing to specify the type!

It's definitely on my list.

**Comment by cinemast** [comment]
Great. Thank you very much for developing catch :+1:

**Comment by philsquared** [comment]
`REQUIRE_THROWS_WITH( expr, message )` (and `CHECK_THROWS_WITH`) is now in (v1.2.1-develop.7)!

This works as `REQUIRE_THROWS`, but with the second argument you can specify a message string for it to match against. The message string supports `*` wildcards at the beginning and/ or end too - and is case insensitive (see examples in last two tests in https://github.com/philsquared/Catch/blob/develop/projects/SelfTest/ExceptionTests.cpp).

**Comment by cinemast** [comment]
Great! Thank you for implementing this.

**Comment by DavidEGrayson** [comment]
If it's case insensitive, I probably wouldn't use it because I want to detect typos in exceptions that my code generates.  (I'm using catch to test a library that will have 3 different implementations for 3 different operating systems, and my tests help ensure that the error messages produced by my code are consistent on all those different platforms.)

Actually, I often want to test the class, the message, and some custom functions on my exceptions, so most of those macros wouldn't work for me.  If REQUIRE_THROWS_AS just returned the exception that got thrown, maybe that would work.  I could imagine a test like this:

~~~~
auto error = REQUIRE_THROWS_AS(throwCustom(), std::logic_error);
REQUIRE(std::string(error.what()) == "something");
REQUIRE(error.custom_method() == something);
~~~~

That's just my two cents.  I don't think Catch needs to support every single use case and I am happy to keep writing try/catch in my tests.

**Comment by philsquared** [comment]
AFAIK there is no way the exception object can be returned - at least not the way you show. Possibly, with conditional compilation for C++11 support, it could be passed into a lambda - but I'm not sure it's worth the mechanics of that (when you can "keep writing try/ catch").

However I have now added Matcher support for the exception messages, at least, so you can do case sensitive compares (as well as StartsWith, EndsWith and Contains).

**Comment by philsquared** [comment]
I believe this ticket can be closed. Please re-open if you feel otherwise

**Comment by vadz** [comment]
Sorry but I can't find any information about the matcher support for this (remember our discussion about the name change? Just try searching for `"CATCH" marcher exception` :-(), could you please point me to any documentation/examples of using it? TIA!

**Comment by philsquared** [comment]
That's an excellent point! Thanks for bringing it up. It looks like I never got around to updating the docs with this change (which is a shame as it's darn useful).

I'll do that shortly.

**Comment by philsquared** [comment]
Done. See near the end of: https://github.com/philsquared/Catch/blob/master/docs/assertions.md#exceptions

Also the Matchers section just below. It's not much right now but should get you going. Let me know if anything is not clear.
