### ISSUE TITLE
Private destructor

### ISSUE THREAD

**Issue by joto** [philsquared/Catch#400]
GCC 4.9 complains about a private destructor when extra warnings are enabled:

    catch.hpp:497:7: error: ‘class Catch::MethodTestCase<C>’ only defines a private destructor and has no friends [-Werror=ctor-dtor-privacy]

This is with `CATCH v1.1 build 14`.

**Comment by PureAbstract** [comment]
* Having a private destructor isn't an error in C++. It's arguably a reasonable thing for a compiler to *warn* about, but it's entirely unreasonable to abort compilation because of it.
* Even if it *were* reasonable to bail on this, it's not entirely accurate in this particular case; `MethodTestCase` has a base class (`IShared`) with a public, virtual destructor through which `~MethodTestCase` can be (and, in fact, is) invoked.

This isn't a problem with Catch, it's a problem with using `-Werror`.

**Comment by joto** [comment]
Okay, ignore the `-Werror`, thats just me calling this code with that option. But there still is the issue with the warning. Can we either make the destructor public or disable that warning? (There are many other warnings disabled in the Catch code, so that would just be another one.)

**Comment by PureAbstract** [comment]
> Can we either make the destructor public

It's private for good reason (specifically, it prevents `MethodTestCase` from being instantiated as a automatic variable) - making it public to silence a warning would make the code more fragile. I don't know who added that warning to GCC, but I very much doubt that they did it with the intention of making code less robust. (This is one of the unintended consequences of a "no warnings" policy - silencing warnings can lead to code that's harder to maintain)

> or disable that warning?

You can do this easily: either pass `-Wno-ctor-dtor-privacy` to gcc, or - even better - include path via the `-isystem` option (instead of `-I`); that way, you disable *all* of the warnings in the header.

The problem with disabling warnings one by one is that you end up with a whole pile of spaghetti `#ifdef this` and `#pragma that` all over the place, to avoid triggering warnings on other compilers. A more subtle problem with a maze of twisty `#pragmas` is it makes it harder for folks developing Catch to find genuinly useful warnings in the code.

**Comment by joto** [comment]
Thanks for the suggestions. This is solved with the new version v1.2.1 which adds a '#pragma GCC/clang system_header' (see also #407).
