### ISSUE TITLE
Consider using `#pragma GCC system_header` to squelch -Weffc++ warnings

### ISSUE THREAD

**Issue by claymation** [philsquared/Catch#407]
Creating this issue as a documentation trail for users looking to silence the -Weffc++ warnings generated when including Catch.hpp. Of course, fixing the cause of the warnings would be great, too.

**Comment by philsquared** [comment]
Thanks for this suggestion (those -Weffc warnings are a pain - especially since I can't work out how to enable them in Xcode any more - but mostly because several of them are just wrong).

I've added ```#pragma GCC/clang system_header```. It seems to work for me in clang. Could you confirm if it works for you in GCC (I don't have a non-clang version of GCC available at the moment) - and especially if it covers all the -Weffc++ warnings?

**Comment by claymation** [comment]
Thanks for looking into this. Using g++-4.9, I needed to use:

    #pragma GCC system_header
    #pragma clang system_header

to squelch the -Weffc++ warnings. Perhaps GCC doesn't understand `#pragma gcc/clang ...`?

**Comment by philsquared** [comment]
Wait. you needed to using the clang pragma on gcc?
By ```#pragma GCC/clang``` I meant that I used ```#pragma GCC``` for gcc and ```#pragma clang``` for clang.
Are you saying it didn't work for you?

**Comment by claymation** [comment]
Oh, I thought you meant, literally, `#pragma GCC/clang ...` :)

Yes, `#pragma GCC system_header` works. I've been using that since I opened this issue, to good effect.

**Comment by horenmar** [comment]
Since this has been fixed for a long time, I am closing this.
