### ISSUE TITLE
Build fails on MacOS X 10.10

### ISSUE THREAD

**Issue by johnwbyrd** [philsquared/Catch#420]
I'm seeing build failures when including the catch library on MacOSX given #95 , apparently due to questionable support of some specific C++11 features on certain configurations of MacOS.

LLVM reports:

> cc -v
> Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
> Target: x86_64-apple-darwin14.3.0
> Thread model: posix

```
In file included from /Users/jenkins/Builds/workspace/hydra-macos-master/src/common/windowmgr.cpp:9:
In file included from ../../../3p/catch/include/catch.hpp:28:
In file included from ../../../3p/catch/include/internal/catch_capture.hpp:11:
In file included from ../../../3p/catch/include/internal/catch_result_builder.h:91:
In file included from ../../../3p/catch/include/internal/catch_expression_lhs.hpp:12:
../../../3p/catch/include/internal/catch_evaluate.hpp:43:17: error: no type named 'nullptr_t' in namespace 'std'
    inline std::nullptr_t opCast(std::nullptr_t) { return nullptr; }
           ~~~~~^
../../../3p/catch/include/internal/catch_evaluate.hpp:43:39: error: no type named 'nullptr_t' in namespace 'std'
    inline std::nullptr_t opCast(std::nullptr_t) { return nullptr; }
                                 ~~~~~^
../../../3p/catch/include/internal/catch_evaluate.hpp:43:59: error: cannot initialize return object of type 'int' with an rvalue of type 'nullptr_t'
    inline std::nullptr_t opCast(std::nullptr_t) { return nullptr; }
                                                          ^~~~~~~
../../../3p/catch/include/internal/catch_evaluate.hpp:165:58: error: no type named 'nullptr_t' in namespace 'std'
    template<Operator Op, typename T> bool compare( std::nullptr_t, T* rhs ) {
                                                    ~~~~~^
../../../3p/catch/include/internal/catch_evaluate.hpp:168:66: error: no type named 'nullptr_t' in namespace 'std'
    template<Operator Op, typename T> bool compare( T* lhs, std::nullptr_t ) {
                                                            ~~~~~^
In file included from /Users/jenkins/Builds/workspace/hydra-macos-master/src/common/windowmgr.cpp:9:
In file included from ../../../3p/catch/include/catch.hpp:28:
In file included from ../../../3p/catch/include/internal/catch_capture.hpp:11:
In file included from ../../../3p/catch/include/internal/catch_result_builder.h:91:
In file included from ../../../3p/catch/include/internal/catch_expression_lhs.hpp:13:
../../../3p/catch/include/internal/catch_tostring.h:25:10: fatal error: 'tuple' file not found
#include <tuple>
```

**Comment by johnwbyrd** [comment]
It seems as though, when building on MacOS X, the llvm libc++ libraries are required in the Xcode project settings.  This means that catch may only be used on MacOS 10.7 and later.

**Comment by kirbyfan64** [comment]
I don't use OSX, but I don't think the version of libstdc++ that OSX had is new enough. You could always try to build a more recent version of libstdc++ or build libc++ yourself.

**Comment by philsquared** [comment]
This ticket is quite old (sorry I didn't notice it at the time). Toolchains in the Apple eco-system tend to move quite fast, so I doubt this issue is still relevant.
I'm marking it for closure, soon, but please let me know (@johnwbyrd, if you're still watching - or anyone else) if you're still having this issue?

**Comment by johnwbyrd** [comment]
I had to drop MacOS 10.6 support because of this dependency.  However, I checked and nullptr_t is part of the C++11 spec, so I have to write this one off because of the age of the compiler.  Closing ticket.

**Comment by philsquared** [comment]
Catch should work fine without `nullptr_t` - it depends only on C++98/03 - but it has support for some C++11 features if available. From what you were saying it sounds like the C++ version detection was not working for you (possibly because of using a different stdlib?). There are ways to fix this: either in Catch, if it's a case of better compiler detection - or in your code (or build settings) as a workaround if it's a case of disabling support for those C++11 features.
However it's not clear if this is still relevant to you?
If it is and you'd like to have another go at this please feel free to re-open the ticket.
