### ISSUE TITLE
Memory leak check for MSVC

### ISSUE THREAD

**Issue by prapin** [philsquared/Catch#439]
Visual Studio C runtime has a debugging mechanism to spot memory leaks.
In the `main` function, `_CrtSetDbgFlag` can be used to enable that mechanism.
When CATCH returns after having executed all tests, MSVC displays the list of memory blocks that have not be freed.
By setting `_crtBreakAlloc` and rerun the test, CATCH will stop at the allocation of the leaked block
(provided the allocation sequence is exactly the same).

See my commit for reference:
https://github.com/prapin/Catch/commit/a4695cc789be7e8434a5ad513fabbf620caa92fc

**Comment by prapin** [comment]
The `_CRTDBG_DELAY_FREE_MEM_DF` flag in my reference commit should in fact be avoided, as it will prevent memory from being physically released.
We only need `_CrtSetDbgFlag(_CRTDBG_LEAK_CHECK_DF | _CRTDBG_ALLOC_MEM_DF);`

**Comment by horenmar** [comment]
If I understand this correctly, its a recommendation/request to hook up with MSVC CRT leak checker into Catch's main, so that memory leaks in tested code can be found?

That is potentially very interesting addition but it might be a while before I can get around to it (but seeing how the issue is from 2015, its been a while anyway).

**Comment by alkhimey** [comment]
It appears in the release notes of https://github.com/philsquared/Catch/releases/tag/v1.8.0. Is this the same feature as described in this issue?

**Comment by horenmar** [comment]
@alkhimey yes
