### ISSUE TITLE
Problems with nullptr in not cpp11 project.

### ISSUE THREAD

**Issue by Grandmother** [philsquared/Catch#445]
Hello, I have a problem where try to compile my test project without cpp11 standard supporting.
Now using a new version of gcc is enough to using nullptr in your test projects, but if I don't use -std=c++11 I got a message that I fool.

May be you can use "__cplusplus" directive to check is cpp11 standard is used? Or may be better to get a choise to user by something like "#define CATCH_CONFIG_NO_CPP11FEATURES"?

[kovtyukhrd@kovtyukhrd ~ ]$ gcc --version
gcc (GCC) 5.1.0

**Comment by vpashka** [comment]
+1
------
gcc --version
i586-alt-linux-gcc (GCC) 5.1.1 20150618 (ALT Linux 5.1.1-alt2)

**Comment by Grandmother** [comment]
vpashka, what whay to solve this problem you prefer?

**Comment by vpashka** [comment]
I mean, I have the exact same problem and her decision, I do not know yet.

**Comment by PureAbstract** [comment]
> I got a message that I fool.

What is the actual message you're getting?

**Comment by vpashka** [comment]
I'm sorry .. I think there was some internal error. Now g++5 normal compiles my tests.

**Comment by philsquared** [comment]
If I read you correctly your issue has gone away?
Either way I have now added the ability to disable C++11 feature use - individually (using, e.g. `CATCH_CONFIG_CPP11_NO_NULLPTR`) or en-masse (`CATCH_CONFIG_NO_CPP11`).

Is your issue resolved?

**Comment by PureAbstract** [comment]
It might also be worth revisiting the logic that (dis|en)ables `nullptr` for gcc (IIRC, currently it's based solely on the gcc version (`__GNUC__` et al)rather than the language version).

Specifically it doesn't check `__cplusplus` to see if C++11 is enabled, so if you're using a reasonably recent version of the compiler with an over-a-decade-old version of the language, you'll see these kind of problems. In fact, I'd consider using *only* `__cplusplus >= 201103` to determine whether to use `nullptr` or not; I doubt there are any vendors who define `__cplusplus` as 201103 or greater who *don't* support `nullptr`, and if there are any, then you can point any related issues back to them where they belong...

**Comment by philsquared** [comment]
Are there any versions of GCC that support `nullptr` but don't set `__cplusplus` to `>= 201103`?
The `__GXX_EXPERIMENTAL_CXX0X__` check in there looks suspicious in that regard. I think I "borrowed" that bit from boost, at some point (I don't have boost sources on this machine to check).

**Comment by Grandmother** [comment]
Hello, I'd find something on this issue:
AFAIUI __GXX_EXPERIMENTAL_CXX0X__ is was used in gcc compilers with version less than 4.7, and after 4.7 version we can check a __cpluslpus. My version is g++ (GCC) 5.1.0 and they probably, remoove the __GXX_EXPERIMENTAL_CXX0X__ support, because they are not experimental now.

**Comment by philsquared** [comment]
After seeing https://github.com/philsquared/Catch/pull/471 I think I follow @PureAbstract's comment now.

We currently have this guard:

    #if __GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 6 && defined(__GXX_EXPERIMENTAL_CXX0X__) )
    #   define CATCH_INTERNAL_CONFIG_CPP11_NULLPTR
    #endif

I think if we just drop the first part (`__GNUC__ > 4 ||`) everything should work (because it will drop down to the later `#if (__cplusplus >= 201103L)` catch-all)?

That seems to make sense. I'm going to make a change on that basis.

**Comment by horenmar** [comment]
Closing this, as it is very old and has been significantly changed since.
