### ISSUE TITLE
BDD actually?

### ISSUE THREAD

**Issue by judgeaxl** [philsquared/Catch#446]
I'm curious about how people use the BDD sections in Catch. I've mostly done BDD in Ruby and Python before (but plenty of "regular" unit testing in C++), and I find that the structure of the BDD macros are a bit odd compared to what I've seen elsewhere.

```
SCENARIO("String manipulation") {
    GIVEN("an empty string") {
        MyString m;
        WHEN("I append a char array") {
            m.Append("stuffs!");
            THEN("it gets appended") {
                REQUIRE(m.Value() == "stuffs!");
            }
            AND_THEN("the length updates") {
                REQUIRE(m.Length() == 7);
            }
        }
    }
}
```

In my opinion, this would only run once through, possibly adding the scenario strings as context to the REQUIRE statements as they are processed. Instead the setup is run four times, the append three, and each REQUIRE is run once. Is nesting the only way to expand on a scenario, so that first this, then that, then that?

Is the idea to try and actually make BDD style testing, or just to apply some of the wording to more classical unit testing?

BDD is otherwise usually written in plain text like this:
```
Scenario: String Manipulation
Given: an empty string
When: I append "stuffs!"
Then: the string equals "stuffs!"
And: the length is 7
```
and you'd have code more like this:
```
CONTEXT() {
   MyString string;
}
GIVEN("an empty string") {
    context.string.clear();
}
WHEN("I append %s") {
    context.string.append(stringParam(0));
}
THEN("the string equals %s") {
    REQUIRE(context.string == stringParam(0));
}
THEN("the length is %d") {
    REQUIRE(context.string.length() == intParam(0));
}
```
So, you're not usually writing sequential code, but having some logic match function calls to your scenarios. Each function here would be called once, with the context managed by the framework.

**Comment by DavidEGrayson** [comment]
Maybe this type of discussion should be on the [Google group](https://groups.google.com/forum/?fromgroups#!forum/catch-forum).

I discovered Catch after using Ruby and rspec a lot, and I like Catch because it is very similar to RSpec.

This is what I might write in RSpec:

~~~~ruby
describe FooBarClass do
  context "when it is constructed from nil" do
    before do
      @foobar = FooBarClass.new(nil)
    end

    it "has a size of 0"
        expect(@foobar.size).to eq 0
    end

    it "has a length of 0"
        expect(@foobar.length).to eq 0
    end
  end
end
~~~~

This can be directly translated to Catch:

~~~~cpp
TEST_CASE("FooBarClass")
{
  SECTION("when constructed from NULL")
  {
    FooBarClass foobar(NULL);
    SECTION("has a size of 0")
    {
      REQUIRE(foobar.size == 0);
    }
    SECTION("has a length of 0")
    {
      REQUIRE(foobar.length == 0);
    }
  }
}
~~~~

I think of this code as defining two different, independent test cases, and I want those test cases to each have their own independent setup so that the order of the test cases is less likely to matter, and they are less likely to have an effect on each other.

If you want the test cases to share some setup variables, the only real reason to do that would be if the setup is particularly slow or expensive in some other way.  If it's fast and cheap, you might as well repeat it for each test case.  RSpec has a `before(:all)` feature you could use for shared setup that would only run once.  Catch doesn't seem to have that, but that's OK.

**Comment by judgeaxl** [comment]
Yes, you're right, the Google group would have been a more fitting venue.

Also, perhaps it's more a matter of style, than anything else. Perhaps I'll play around with special sections that don't run in isolation, just to avoid the "strangeness" of the GIVEN section being run on its own initially, which currently would be the equivalent of Setup(), or before() being run on their own without any actual testing.

**Comment by philsquared** [comment]
Hi @judgeaxl,

Yes, whether you are using SECTIONS or the BDD-style wrappers for them, you'll need to nest for them to run in sequence. Peer SECTIONS are run in isolation from each other.
See my NDC Oslo talk for an example (about half way through):
https://vimeo.com/131632252
