### ISSUE TITLE
Option to run test in process isolation

### ISSUE THREAD

**Issue by ssylvain** [philsquared/Catch#462]
Feature request.

It would useful to have the option to run tests using process isolation. In other words, launch each test in a child process. This would protect against things like stack corruption and offer a better guarantee that tests are isolated.

Something similar to this: https://msdn.microsoft.com/en-us/library/windows/hardware/hh439732(v=vs.85).aspx

**Comment by gsauthof** [comment]
This is also implemented by [Check](http://check.sourceforge.net/doc/check_html/check_2.html#Unit-Testing-in-C) (a unittesting library for C). Check enables its fork mode by default (it forks before each test case). The fork mode can be disabled via an environment variable or via calling an API function.

**Comment by joe-jordan** [comment]
This was a gotcha with `catch` for me - I am used to `check` (while writing pure C), but `catch` was recommended for a C++ project I am working on. I *assumed* that it would run each test in a forked process, but discovered to my surprise that some static initialisation was conserved between tests! 

I would call this a bug rather than a feature request: buggy C++ can segfault just as much as buggy C.

**Comment by nabijaczleweli** [comment]
>in a forked process

Except for Windows world where processes are expensive and forking is hard :v

**Comment by joe-jordan** [comment]
hmm, then how about something like

    #define CATCH_CONFIG_FORKED_MAIN
    #include <catch.hpp>

? This leaves it off by default (and doesn't change the behaviour of existing tests), but makes it an option for people who need it.

**Comment by Darelbi** [comment]
You can still invoke catch and run specific tests. Instead I would add a
feature that allow a batch script to query the number of tests so that we
can loop and invoke it once for each number going from 0 to NUMBER-1. Does
that make sense? Effectively I was hitted sometimes by a crash that prevent
further tests to run, would be great fix that.

2016-09-05 11:40 GMT+02:00 Joe Jordan <notifications@github.com>:

**Comment by joe-jordan** [comment]
Why do we need to push the complexity into the test runner, when we have C++ to do this for us?

**Comment by onqtam** [comment]
@Darelbi querying how much tests pass the current run criteria and then invoking the process multiple times with different ranges indeed isn't such a big deal (a shameless plug - [doctest](https://github.com/onqtam/doctest/blob/master/doc/markdown/commandline.md) supports this with the ```--count``` flag and ```--first=x``` ```--last=y```). But the downside is you don't get one summary for all tests

**Comment by rollbear** [comment]
I think this would be great, and having experience working with test systems that do this, I can speak from experience. The stability in the face of crashing bugs is a nice bonus, but it's a minor thing. The big thing is the isolation - that you never have to worry about what state a test case leaves the system in. Even horrible designs with singletons (shudder) become reasonably easy to test, since whatever messy state you leave the singleton in is forgotten once the test has run to completion, regardless of whether it passed or failed.

**Comment by Darelbi** [comment]
To get one summary we have to either:

- Have catch to run tests in isolation: it could in example spawn a new
process by passing same arguments + test_ID (in example if forking is not
feasible)
- Each catch run produce a partial report => so results get aggregated (it
could even use some sort of cache so that when we ask for results it is
showed in a readable manner).

speculating here.

2016-09-05 13:51 GMT+02:00 Björn Fahller <notifications@github.com>:

**Comment by lightmare** [comment]
> @Darelbi Instead I would add a feature that allow a batch script to query the number of tests so that we can loop and invoke it once for each number going from 0 to NUMBER-1.

You can achieve that with current Catch already.
```sh
./runner --list-test-names-only | xargs -d'\n' -n1 ./runner
```

**Comment by horenmar** [comment]
Since this will not be added to Catch Classic, but might be added to Catch 2 at some point, I opened #853 instead.
