### ISSUE TITLE
Clion highlights TEST_CASE and SECTION as spurius syntax errors

### ISSUE THREAD

**Issue by cossio** [philsquared/Catch#484]
I don't know why this happens, but if I have a .cpp files with more than one TEST_CASE, the second TEST_CASE and all that follow are highlightes as syntax errors in CLion IDE, even if the code compiles well.

**Comment by rollbear** [comment]
There's a bug report that CLion doesn't respect the __LINE__ macro, which causes this kind of problem for pretty much all C++ unit test and mocking frameworks.

See https://youtrack.jetbrains.com/issue/CPP-2801 for details.

There's another report for the __COUNTER__ macro.

https://youtrack.jetbrains.com/issue/CPP-820

**Comment by cossio** [comment]
Oh, so it's a problem with CLion, not Catch. Good to know. Hope they fix it. Thanks for your reply.

**Comment by rollbear** [comment]
You may want to +1 and/or star mark them to give Jetbrains your sense of urgency.

**Comment by russdamerell** [comment]
Is this still an issue with Clion? Is it more an annoyance and are you still able to use Clion and Catch together productively?

**Comment by horenmar** [comment]
@russdamerell The author is currently using CLion to work on Catch, so I'd say it is ok.

Not sure if there is still problem with `__COUNTER__` macro, CPP-820 is still open and Catch prefers to use it if possible.

**Comment by philsquared** [comment]
An update on this.
At time of writing Clion still has a problem with `__COUNTER__` - so if Catch detects that it can use it there are still issues.

Here's the three stage approach for dealing with this:

1. In the immediate term if you have these issues #define 
2. The next release of CLion should have an identifier that is #defined during the IDE parsing stage and Catch will automatically disable use of `__COUNTER__` when this is set (so you shouldn't need the workaround in (1) above).
3. I know, from internal discussion, that the `__COUNTER__` issue will be fixed in he mid-term future. That's not on the public roadmap yet, so I can't say when, but for our purposes here (2), above, should be enough for us.

Once the CLion identifier workaround in (2) is released I'll close this.

**Comment by horenmar** [comment]
Can someone confirm that the new CLion version is OK now?

**Comment by philsquared** [comment]
The latest CLion *EAP* version is ok now. But that won't be released as an official version until the end of the month, so I'm inclined to leave this open until then.

https://blog.jetbrains.com/clion/2017/03/clion-2017-1-eap-disassembly-view-catch-msvc-changes/

**Comment by horenmar** [comment]
New CLion was released, so this should be ok now.
