### ISSUE TITLE
--list-test-names-only option generate failure exit code (non zero)

### ISSUE THREAD

**Issue by paulobrizolara** [philsquared/Catch#509]
Hi!
I am trying to use the "--list-test-names-only" on my build script (waf script), so that i can execute each test separately posteriorly.

However, when i run the tests (only) with this option, Catch returns a non zero value and the build system thinks that the task failed.

My test main function is essentially the code below:

    int main( int argc, char* const argv[] ){    
        Catch::Session session; // There must be exactly once instance
        int returnCode = session.applyCommandLine( argc, argv );
        if( returnCode == 0 ){ // returnCode != 0 indicates a command line error
            returnCode = session.run();
        }
    
        return returnCode;
    }

I believe that the problem is that "session.run()" is returning the number of tests listed (the value returned correspond to the number of tests that i have). 

I would like to know if this is by design or if is some kind of bug. On the first case, what could i do to avoid breaking the build when listing the test cases.

Obs.:
Debugging the execution, i found out that the 'returnCode' value is coming from this section of code on the "run" function (in Catch.hpp):

    // Handle list request
    if( Option<std::size_t> listed = list( config() ) )
        return static_cast<int>( *listed );

**Comment by philsquared** [comment]
This is by design. I use this in my own build system to be able to obtain the number of tests available from a script without having the parse the textual output.
I'm surprised you have no way of ignoring the return code in your build script. I might consider, in the future, making the return code behaviour configurable there - but I don't think I'll get to that very soon.

So in the meantime the best workaround I can think of for you is to add the proverbial "extra level of indirection". Invoke Catch from another script (probably just a shell script/ batch file - need only be one line) - at least for the test listing case - and ignore the return code.

**Comment by paulobrizolara** [comment]
Sorry, i thought that i had closed this issue before.

I have found a workaround (essentially, ignoring the returned code).
It is not pretty but is nothing important, so i will not bother anybody with that.

Thanks for the answer.
