### ISSUE TITLE
Make Catch precompiled headers friendly

### ISSUE THREAD

**Issue by SergiusTheBest** [philsquared/Catch#513]
Tests are compiled slow without precompiled headers. I managed to put Catch into precompiled headers and that gave a huge compile time boost. But the process is not as straightforward as it should be:
 
stdafx.h (a standard precompiled header):
```
#include <catch.hpp> 
```
test1.cpp (a file with tests)
```
#include "stdafx.h"
```
main.cpp (a file with the entry point)
```
#define CATCH_CONFIG_MAIN
#include <catch.hpp>
```
The trick is to disable precompiled headers for the `main.cpp`. Otherwise it doesn't work.

What I want is to be able to include `main` function without `CATCH_CONFIG_MAIN` so I can use precompiled headers in every file. For example using `#include <catch_main.h>`. Thus there will be a fast build without any special configuration.

**Comment by philsquared** [comment]
Disabling PCH for the main cpp file is exactly what I do - for the same reasons.
It's not possible to use Catch without `CATCH_CONFIG_MAIN` or `CATCH_CONFIG_RUNNER` in one source file - because this is what causes Catch do compile in all the implementation code (i.e. what would normally be in cpp files). In general I have my main cpp file *only* do the `#define` and `#include` (and possibly some other one-time Catch related things, like setting up exception translators). I've not found this to cause any undue slowness.

If you do want to achieve the same effect as having a pch for your main file you might be able to compile it as a static lib once and use that instead of the cpp file? (I've not tried that and I'm not sure how that interacts with main() being in a lib). If that works you'd only have to recompile the lib any time you get a new version of Catch.

**Comment by philsquared** [comment]
Oh, and do make sure you're familiar with: https://github.com/philsquared/Catch/blob/master/docs/slow-compiles.md

**Comment by SergiusTheBest** [comment]
I measured timings for building a `test1.cpp`: 800 ms vs 600 ms. So yes, puting `Catch.h` into pch is not required. The question is closed. Thanks!
