### ISSUE TITLE
What's wrong with ConfigData?

### ISSUE THREAD

**Issue by alialsalim** [philsquared/Catch#514]
Hi, I am a new user of Catch framework. It's so amazing
However, the configData looks like doesn't work with vector contains 2 test tab/test name.
Here is my code:
```cpp
int main( int argc, char\* const argv[] )
{
     Catch::Session session; 

 Catch::ConfigData m_ConfigData;
 vector<string> testOrTag;
 testOrTag.push_back("[Sum]");
 testOrTag.push_back("[Sum1]"); // It will work if you remove this line
 m_ConfigData.testsOrTags = testOrTag;
 session.useConfigData(m_ConfigData);
    cout <<"TEST RESULT: " << session.run() << endl;

return 0;
}
```

If I only push one test tag to vector ( [Sum] or [Sum1] ), it works. But if i push 2 test tags to vector as above, it returns "No test ran". 

This is my test cases:

```
TEST_CASE( "Simple Test", "[Sum]" )
{
    SECTION("Sum 1 and 1")
    {
        REQUIRE( cal.Sum(1,1) == 2);
    }

SECTION("Sum 1 and 2")
{
    REQUIRE( cal.Sum(1,2) == 3 );
}

}

TEST_CASE( "Complex Test", "[Sum1]" )
{
    SECTION("Sum 100 and 100")
    {
        REQUIRE( cal.Sum(100,100) == 200);
    }

SECTION("Sum 100 and 200")
{
    REQUIRE( cal.Sum(100,200) == 300 );
}

SECTION("Sum 1000 and 3000")
{
    REQUIRE( cal.Sum(1000,3000) == 4000 );
}

}
```

Can you explain why? Is this a bug or Did i do something wrong?
Thank you so much

**Comment by philsquared** [comment]
Whether you split them over several strings in the vector, or put them all in a single string, a series of tags forms an AND expression (so *all* the tags must match). To OR tags together use a comma. It's easier to do that in a single string, e.g.:

  `testsOrTags.push_back("[Sum],[Sum1]");`

`testsOrTags` is really only a vector as an artefact of the way it's read from the command line (because space separated arguments come through individually). I could change that to just append to a single string - which might make it clearer when you're populating it programmatically - but I'm not sure it's worth it. I don't think it's used very much (I could be wrong).

The ANDing and ORing is described in the docs for the command line, btw:

https://github.com/philsquared/Catch/blob/master/docs/command-line.md#specifying-which-tests-to-run

**Comment by philsquared** [comment]
@alialsalim did that answer your question? Can I close the issue?

**Comment by horenmar** [comment]
Since there hasn't been a followup in over a year, I am going to close this.
