### ISSUE TITLE
REQUIRE macro can't take templates with more than one templated parameter

### ISSUE THREAD

**Issue by chrisb2244** [philsquared/Catch#518]
The error messages are:

**gcc**:

    error: macro "REQUIRE" passed 2 arguments, but takes just 1
    In function 'void ____C_A_T_C_H____T_E_S_T____311()'
    'REQUIRE' was not declared in this scope
        REQUIRE(myTemplateFct<int, double>());

The number changes but the output is similar.

**clang**:

    error: too many arguments provided to function-like macro invocation
        REQUIRE(myTemplateFct<double, int>());
    
    /path/to/catch.hpp:9333:9: note: macro 'REQUIRE' defined here
        #define REQUIRE( expr ) INTERNAL_CATCH_TEST( expr, Catch::ResultDisposition::Normal, "REQUIRE" )
        ^
    catchInc.cpp:8:5: error: use of undeclared identifier 'REQUIRE'
        REQUIRE(myTemplateFct<double, int>());

The code to compile is:

    #define CATCH_CONFIG_MAIN
    #include <catch/catch.hpp>

    template<typename T, typename U>
    bool myTemplateFct() { return true; }
    
    TEST_CASE("Example") {
        REQUIRE(myTemplateFct<int, double>());
    }

On the other hand, this does work:

    TEST_CASE("Example") {
        bool a = myTemplateFct<int, double>();
        REQUIRE(a);
    }

**Comment by philsquared** [comment]
This is the class short-coming of macros in general. Because macros are unaware of C++ syntax (and templates, in particular) they do not recognise the '<' and '>' brackets as anything special - and so see the ',' in the middle as a macro argument separator.

The usual workarounds are:
(a) specify your types outside the macro - either as you have done, or by using a typedef.
(b) place the type definition in parentheses, e.g.:

  'REQUIRE( (myTemplateFct<int,double>()) );'

HTH

**Comment by chrisb2244** [comment]
Aha! I figured the problem was something like that, but thank you for the quick solution (b).
