### ISSUE TITLE
Catch header should include <memory>

### ISSUE THREAD

**Issue by masterl** [philsquared/Catch#551]
Since you guys use std::auto_ptr (which is deprecated, btw...), you should include < memory >.

I grabbed the single_header from release *v2.0.0-develop.1* and simply compiled an empty test:

```c++
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
```

This is what I got:
![screenshot_2015-12-09_06-03-46](https://cloud.githubusercontent.com/assets/5068286/11679750/a83d357a-9e3a-11e5-82a9-27fe50b57f3f.png)

---

If I include <memory> before:
```c++
#include <memory>
#define CATCH_CONFIG_MAIN
#include "catch.hpp"
```

Then it compiles:
![screenshot_2015-12-09_06-06-26](https://cloud.githubusercontent.com/assets/5068286/11679804/0898e126-9e3b-11e5-9f7f-b9f8b9482d82.png)

---
Xubuntu 15.10
```
▶ g++ --version
g++ (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010
```

Simple compilation with: `g++ -Wall -std=c++14`

**Comment by masterl** [comment]
Just fiy, the extra output on the screenshots are just `echo` from my makefile, so there are no unknown stuff happening.

**Comment by philsquared** [comment]
Looks like I already fixed that. I didn't think anyone was looking at v2 yet so I updated it in-place (rather than inc the build #). Could you check the timestamp at the top of the generated header and compare it with this:
https://github.com/philsquared/Catch/commit/693355cc7530535c2b43a85da775ea4901b67eb6

Assuming you have the 8:41 version please grab the newer one and try that.
You'll notice, too, that the updated commit uses `CATCH_AUTO_PTR` instead of `std::auto_ptr` directly. If the ability to use `std::unique_ptr` is detected it will use that instead.

**Comment by masterl** [comment]
Yes, it's the 8:41.

```
 *  Catch v2.0.0-develop.1
 *  Generated: 2015-11-23 10:08:41.422349
```

Nice, thank you!
