### ISSUE TITLE
Qt args interfere with CATCH, prevent tests from running.

### ISSUE THREAD

**Issue by SebastianTroy** [philsquared/Catch#605]
Catch assumes that all command line arguments are for it.

Qt by default passes the path to the executable as a programs first arg. I believe that this is filtering which tests are run even though the arg is completely unrelated to Catch. I can get around this by modifying argc and argv before passing them to catch but this is ugly and prone to breaking.

Perhaps CATCH should ignore strings with the .exe extension? Or be more selective in what it interprets as a test filter?

Even better would be if Catch could ignore any arguments not sandwiched between an optional "catchstart" and "catchend" arg pair, allowing for instances where Catch is being run within a program that requires args unrelated to catch.

**Comment by horenmar** [comment]
First of all, does first argument mean `argv[0]`? Because if so, that is standard behaviour, and Catch accounts for that properly. If that means `argv[1]`, why would it do that?

Anyway, ignoring arguments ending in `.exe` would maybe work on Windows, but not on other systems, and if you need to pass arguments that are not meant for Catch to Catch test binary, then you really need your own main and fix them up.

**Comment by horenmar** [comment]
Since there hasn't been a follow up in 3 weeks, I am going to close this issue.
