### ISSUE TITLE
 Missing Sanity Check for malloc() in catch.hpp

### ISSUE THREAD

**Issue by dogbert2** [philsquared/Catch#610]
Missing Sanity Check for malloc() in catch.hpp

There appears to be a missing sanity check for malloc in directory
'src/catch', file 'catch.hpp' as the code segment below shows:

```
inline size_t registerTestMethods() {
    size_t noTestMethods = 0;
    int noClasses = objc_getClassList( CATCH_NULL, 0 );

    Class* classes = (CATCH_UNSAFE_UNRETAINED Class *)malloc( sizeof(Class) * noClasses);
    objc_getClassList( classes, noClasses );
```

**Comment by nabijaczleweli** [comment]
What kind of a "sanity check"? All multiplications/length seem to be correct.
Well, using `malloc()` is a questionable matter in and of itself.

**Comment by kirbyfan64** [comment]
@nabijaczleweli `malloc` returning `NULL`.

**Comment by kirbyfan64** [comment]
Though this really should be `classes = new Class[noClasses]`...

**Comment by nabijaczleweli** [comment]
This should be a smart pointer :v

**Comment by philsquared** [comment]
@dogbert2 - you are technically correct (which is the best kind of correct). However I don't think it's a big deal here. This is called immediately on entering `main()` - and there's nothing you can do to recover from it. If you're out of memory for this call then the changes of something like iostreams working is pretty low too.

@kirbyfan64 and @nabijaczleweli bear in mind this is Objective-C code (well, technically it's C code in an Objective-C context, reflecting over Objective-C code). That memory handling needs to interact with ARC (Automatic Reference Counting) - and also stick around for the lifetime of the program since instances of the Class object are kept around. I'm sure it could be cleaned up but it's tricky stuff that's been "just working" for years now without any need to touch it.

**Comment by horenmar** [comment]
I agree with Phil here, if things went wrong so soon, then there is nothing to do, except maybe explicitly exit.
