### ISSUE TITLE
Catch program mysteriously won't run

### ISSUE THREAD

**Issue by nsmith22** [philsquared/Catch#692]
I recently ran into an issue where I accidentally duplicated a TEST_CASE name.  After doing that, running my test program from Visual Studio was returning immediately with exit code 1.  I have a custom main() function and putting a breakpoint on line 1 was not hitting.  For a while, I could not figure out why my test program all of a sudden stopped working and with seemingly no explanation (nothing unusual coming out in VS console, unable to debug it, etc).

Finally, I ran the same test program from console outside of VS and saw the problem being emitted in my console via std out.

This is not really a bug, but a usability issue.  I would like that this problem be more obvious to the programmer, or possibly the problem should be suppressed until Catch::Session().run() is called so that debugging this problem is easier.  Another option is to emit a special error code and document that (have not been able to find documentation on this problem in GitHub).

Lastly, THANK YOU for this project.  I use it all over my codebase with great success and tell many people about it.

**Comment by philsquared** [comment]
Thanks for the feedback. I'll certainly consider that (probably for Catch2 at this point).
And thanks for spreading the word :-)

**Comment by philsquared** [comment]
@nsmith22 Since you reported a change was made so that duplicate test names cause an exception to be thrown instead of just terminating.
Does this change anything for you? (I appreciate it's a while ago you brought this up).

**Comment by horenmar** [comment]
Currently, in Catch 1.9.4, startup configuration errors lead to exception being thrown before main is entered. This is not ideal, because this leads to implementation specified behaviour (well, std::terminate is always called, but what happens in the handler is up to the implementation), but should make it fairly clear that something bad is happening.

Development branch of Catch 2 incorporates a change where exceptions from configuration errors are instead *stored* and consumed after Catch enters main. Note that if you supply your own main, you might have to handle these exceptions yourself (see documentation in the Catch 2 branch).


Since there has been no followup on this issue for ~3 months and current master already incorporates a partial fix, I am closing this issue.
