### ISSUE TITLE
Abort exection if the whole test suite runs longer than specified time

### ISSUE THREAD

**Issue by obfuscated** [philsquared/Catch#712]
One of our tests just discovered a dead-lock issue in the code. The result is that the test executable never finished. This happened on a local machine, so it is manageable, but it will be pretty bad if it happens on a build machine.

Could you add a feature to catch that automatically fails the test suite if certain runtime is exceeded?

**Comment by philsquared** [comment]
That'll be pretty hard to do in the current, thread-agnostic, implementation - at least in the code.
Most build server systems will let you specify a runtime threshold for tests for exactly that reason already (I know TeamCity certainly does). Otherwise you could call it from a script that does the timeout.
Which build system are you using?

I'll be adding threading support in Catch2 and it makes sense to have something like this built in for that.

**Comment by obfuscated** [comment]
A custom built one and cmake. I know it will be hard to do and still work with gcc/vc++/icl/clang/no-c++11.
We can do it ourselves using our threading apis, but I think it will be a good thing to have in the vanilla catch.

**Comment by horenmar** [comment]
Since this will not be implemented in Catch Classic, I am going to close it in favour of overarching issue #853.
