### ISSUE TITLE
Catch cannot compare values with CHECK() on x86

### ISSUE THREAD

**Issue by acki-m** [philsquared/Catch#740]
It seems strange, but with the newest version of catch I got for a simple comparison of numbers now a false test value.
```
uint64_t get_value()
{
    return 3147483640;
}
TEST_CASE("some test", "[test]")
{
    CHECK(get_value() == 3147483640); // this will result in an error...
}
```

It happens only on x86 and with compilers: MinGW, gcc and clang.

**Comment by lightmare** [comment]
You need to use the `unsigned` suffix: `3147483640u`. Or perhaps even better, `#include <stdint.h>` and use `UINT64_C(3147483640)` macro. Otherwise the literal is of type `int`, which on 32-bit has a maximum value of `2147483647`. It doesn't matter that your function returns `uint64_t`. The `3147483640` literal loaded into `int`, overflows and becomes negative, and then when it's converted to `uint64_t` becomes a totally different value.

**Comment by acki-m** [comment]
with catch 1.2.1 it worked. With 1.5.7 I get now this error.

```
 CHECK( var.get_value<uint64_t>() == 3147483640 )
ith expansion:
 3147483640 (0xbb9ac9f8)
 ==
 3147483640 (0xbb9ac9f8)
```

But adding changing it to: `3147483640u`
```
 CHECK( var.get_value<uint64_t>() == 3147483640u )
```
it worked for me now...

**Comment by lightmare** [comment]
Found another recent issue #730 showing the same problem; in a more obvious way, IMO, so I'm going to comment more on that one.

**Comment by horenmar** [comment]
I am probably going to close this one, we can talk about how messy the comparison internals are in #730.
