### ISSUE TITLE
Misleading toString documentation regarding overloads

### ISSUE THREAD

**Issue by mickk-on-cpp** [philsquared/Catch#741]
The documentation for string conversions offers the [following advice](https://github.com/philsquared/Catch/blob/e27c4ee04282f60aefcc9b1062a74f92cf6c1a2b/docs/tostring.md#catchtostring-overload) (abridged):

```c++
namespace Catch {
    std::string toString( T const& value ) {
        return convertMyTypeToString( value );
    }
}
```
> Note that the function must be in the Catch namespace, which itself must be in the global namespace.

Unfortunately this advice is not quite correct. The following program will not give the desired behaviour when compiled with GCC or Clang:

```c++
#define CATCH_CONFIG_MAIN
#include "catch.hpp"

namespace user {

struct udt {};
constexpr bool operator==(udt, udt) { return false; }

} // user

namespace Catch {

std::string toString(user::udt) { return "udt"; }

} // Catch

TEST_CASE( "demo" )
{
    CHECK( user::udt {} == user::udt {} );
}

```

When the resulting program is run, the report displays the expansion as `{?} == {?}`, i.e. the overload provided by the user has not been found. That overload cannot be found because it is declared after the point of use (which is inside `catch.hpp`). This can be observed by tweaking the program so that the overload is declared before use:

```cpp
#include <string>

namespace user {

struct udt {};
constexpr bool operator==(udt, udt) { return false; }

} // user

namespace Catch {

std::string toString(user::udt) { return "udt"; }

} // Catch

#define CATCH_CONFIG_MAIN
#include "catch.hpp"

TEST_CASE( "demo" )
{
    CHECK( user::udt {} == user::udt {} );
}
```

This time the expansion is shown as `udt == udt`, as expected. Here is a [dumbed-down program schema on Coliru](http://coliru.stacked-crooked.com/a/cdf8130640823c77) to outline the situation more precisely.

This is not a problem for the other advice regarding string conversions, namely using `operator<<` or a partial specialization.

**Comment by onqtam** [comment]
The code that doesn't work actually doesn't work only for conforming compilers such as clang and gcc - it actually works with MSVC because of their broken two phase lookup.

To get it working for all compilers you would need to move the overload into the user namespace instead of Catch. I think this has to do with ADL - but I'm no C++ expert.

Thanks for this catch (pun intended) - [doctest](https://github.com/onqtam/doctest) has the same problem in the documentation!

**Comment by mickk-on-cpp** [comment]
I don't know Catch internals that well, but from the look of it `toString` is meant to be called qualified ([example](https://github.com/philsquared/Catch/blob/35f510545d55a831372d3113747bf1314ff4f2ef/include/internal/catch_expression_lhs.hpp#L74)). So no ADL.

**Comment by HeroicKatora** [comment]
Another way to work around this would be with explicit class template specialization, or even a combined way. [Both possiblities in one file](http://coliru.stacked-crooked.com/a/6041a50a015e1db2)

**Comment by horenmar** [comment]
Catch 2.0 will have some changes to how Catch stringifies types, namely using `toString` overloads will be removed, because they caused more trouble than they were worth.

Only `StringMaker` specialization and `operator<<` overloads will be supported in the future.

Anyway, I am going to update the documentation and close this issue in the meantime
