### ISSUE TITLE
Get more logging information ? 

### ISSUE THREAD

**Issue by scm-ns** [philsquared/Catch#768]
The features I am testing takes some time to compute, so I was wondering if there was feature in Catch that allowed logging so that I can know which part of my code is being tested right now? I used INFO but  it seems to need a failure for reporting. WARN does what I want, but this is not really a warning but logging? Is there something I can do here? Can I contribute? If so could someone give me some pointers, else is there an already existing feature that does this? I wanted to add something like LOG. 

I am new to open source, if I am doing anything wrong, please let me know. 
Thanks !

**Comment by lightmare** [comment]
You want immediate response on stderr, no need to have a macro for that:
```c++
std::cerr << "we're here\n";
```

**Comment by horenmar** [comment]
My personal opinion is that if what you want is unconditional logging of running code (as opposed to logging of finished tests), then you need a logging framework, which is orthogonal to unit tests and probably shouldn't be part of Catch. (And `std::clog` can serve as a very minimal logging implementation)

On the other hand, if you have a ton of long running tests and want to know which one already passed, you could pass `-s` to the Catch generated binary. This make it report tests that finished successfully in addition to those that failed. I strongly recommend passing `-r compact` as well, because the default reporter can be rather verbose if you want all tests to be reported.

**Comment by horenmar** [comment]
I am going to close this, since it has remained inactive for ~3 weeks.
