### ISSUE TITLE
What's the minimum gcc version for Catch?

### ISSUE THREAD

**Issue by ruipacheco** [philsquared/Catch#802]
## Description
I'm trying to build a project with gcc 4.8 as I believe is the earliest gcc release with full C++11 support. But a project that builds perfectly with Clang fails on GCC.

### Steps to reproduce
Replace Clang with GCC 4.8 and build the project. The following errors appear: 

https://gist.github.com/ruipacheco/f2979dbb4c94866aac1143467453ed4f

I've reduced my tests to a single main that is composed of this:

```
#define CATCH_CONFIG_RUNNER
#include <catch.hpp>

int main(int ac, char* av[]) {
  int result = Catch::Session().run(ac, av);
  return result;
}
```

* Catch version: **1.5.8**, **1.6.0**, **1.6.1**, **1.7.0**
* Operating System: **Latest OSX Sierra**
* Compiler+version: 

ruihpacheco at descartes in ~/chi/databaseclient/cpp/ninja (default)
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/opt/local/libexec/gcc/x86_64-apple-darwin16/4.8.5/lto-wrapper
Target: x86_64-apple-darwin16
Configured with: /opt/local/var/macports/build/_opt_bblocal_var_buildworker_ports_build_ports_lang_gcc48/gcc48/work/gcc-4.8.5/configure --prefix=/opt/local --build=x86_64-apple-darwin16 --enable-languages=c,c++,objc,obj-c++,lto,fortran,java --libdir=/opt/local/lib/gcc48 --includedir=/opt/local/include/gcc48 --infodir=/opt/local/share/info --mandir=/opt/local/share/man --datarootdir=/opt/local/share/gcc-4.8 --with-local-prefix=/opt/local --with-system-zlib --disable-nls --program-suffix=-mp-4.8 --with-gxx-include-dir=/opt/local/include/gcc48/c++/ --with-gmp=/opt/local --with-mpfr=/opt/local --with-mpc=/opt/local --with-isl=/opt/local --disable-isl-version-check --with-cloog=/opt/local --disable-cloog-version-check --enable-stage1-checking --disable-multilib --enable-lto --enable-libstdcxx-time --with-build-config=bootstrap-debug --with-as=/opt/local/bin/as --with-ld=/opt/local/bin/ld --with-ar=/opt/local/bin/ar --with-bugurl=https://trac.macports.org/newticket --with-pkgversion='MacPorts gcc48 4.8.5_0' --with-build-config=bootstrap-debug
Thread model: posix
gcc version 4.8.5 (MacPorts gcc48 4.8.5_0)

**Comment by horenmar** [comment]
You are very likely missing flag telling gcc to link in the standard library, which is why you are seeing all the missing references to things like `std::basic_string<...>::empty()` or `___cxa_free_exception`.

One possibility is to actually use g++, as it links in the C++ standard library by default, the other is to add it manually (quick test says that `gcc test.o -std=c++11 -lstdc++` links and runs, but you might want to be careful to link in libraries with the proper "bitness").


As to the original question in the issue, IIRC the lowest tested one is something like gcc 4.2 on mac, but currently only 4.8 and up are built as part of CI builds.

**Comment by ruipacheco** [comment]
Thanks!
