### ISSUE TITLE
MSVC: Windows macros NOMINMAX and WIN32_LEAN_AND_MEAN are redefined

### ISSUE THREAD

**Issue by PeterSchuebel** [philsquared/Catch#803]
I'm building a project on Windows using MSVC 2013 and Catch. After updating from Catch v1.6.1 to v1.7.0 I encounter build errors regarding redefined macros NOMINMAX and WIN32_LEAN_AND_MEAN. 
In the file D:\src\Catch\include\internal\catch_fatal_condition.hpp these are now defined just before including <windows.h> and then undefined straight away.
All other Catch code has the definition of these macros inside some guards, e.g.: #ifdef CATCH_DEFINES_NOMINMAX

The same approach should be made for this instance in catch_fatal_condition.hpp.

* Catch version: **v1.7.0**
* Operating System: **Windows 7, 8.1**
* Compiler+version: **Microsoft Visual Studio 2013 C++**

**Comment by PeterSchuebel** [comment]
suggested fix:
[1625_WindowsMacrosFix.txt](https://github.com/philsquared/Catch/files/750520/1625_WindowsMacrosFix.txt)

**Comment by horenmar** [comment]
Can you try the attached single header file? It was an artifact of changes being pulled in from separate branches, so that when branch `windows-header-defines` changed the inclusion pattern, the `dev-signals` branch was not yet in.

[catch.zip](https://github.com/philsquared/Catch/files/750526/catch.zip)

**Comment by PeterSchuebel** [comment]
Ah, that makes sense.
Yes, the file you sent works on my project both in Debug and Release.
