### ISSUE TITLE
.Net, XSLT, Notepad++ etc. do not support XML 1.1

### ISSUE THREAD

**Issue by mKlus** [philsquared/Catch#808]
The xml reporter/XML writer uses XML 1.1 that is not widely supported yet.
We can't parse the XML result file in .Net (4, 4.5.2 nor 4.6.2), can not use XSLT to transform it into html and also Notepad++ can not parse it. None of them support XML 1.1.

Can we "downgrade" back to XML 1.0?

**Comment by horenmar** [comment]
Well, XML 1.1 is only 13 years old at this point, it will take off any moment now :smile:

Bit more seriously, it was changed to 1.1 because of some encoding issues. I will check if that is still relevant and if its not, then we don't have problems with going back to 1.0

**Comment by mKlus** [comment]
Any moment from between now and 2030 I guess. :-)
I was actually quite surprised that it's still not supported in .Net 4.6.2.

It would be nice if we at least have a define or a command option which we can disable the XML 1.1 with...

**Comment by philsquared** [comment]
The problem here is that people do have a need to encode characters in their output that are not supported by XML 1.0 (although there is some doubt over that, due to a later, unnumbered, edition of XML 1.0 supporting more characters).

But XML 1.1 does indeed seem to be problematic. So I'm looking at how to have things both ways. I don't like the idea of a runtime or compile time switch to choose.

So I'm experimenting with the idea of C-escaping the problematic characters (e.g. `\x01`) instead of encoding them - so as far as the XML parser is concerned there are only XML 1.0 allowable characters - and it is up to the user to interpret the escaping.
Given that the control characters in question are rarely encountered in actual output I think this is probably fine - but I'm interested in others thoughts here.

I'm committed these changes to the following branch, so you can try it out:

https://github.com/philsquared/Catch/tree/Xml1_0

**Comment by mKlus** [comment]
Hi Phil, thanks for looking into this. Would you be able to rebase (or marge with) the XML1_0 branch on top of v1.7.1 (or master)?

Had a quick look at the changes and the below code looks like it should call writeDeclaration() method instead of writing the declaration itself?
`
        XmlWriter( std::ostream& os )
        :   m_tagIsOpen( false ),
            m_needsNewline( false ),
            m_os( os ),
            m_xmlVersion( XmlEncode::_1_0 )
        {
            *m_os << "<?xml version=\"1.1\" encoding=\"UTF-8\"?>\n";
        }
`

**Comment by philsquared** [comment]
Do you mean that you tried to merge it yourself?

If and when I merge to master I suspect it will require a bit of fix-up, yes, since I've made other changes to the xml writer (and managed to screw up the history a bit with a couple of reverts).

I think I'll be merging it in shortly.
If you meant something else please let me know.

**Comment by mKlus** [comment]
Yeah I tried merging it myself but not 100% sure that I did it correctly :)
I have couple more changes in my repo so needed to be careful... 

The 2 changes I have are:
- write stylesheet reference to the xml (xml reporter and xml writer change)
- write description and tags attributes to the TestCase and Section elements (xml reporter change)

I think you could consider those changes to be added to the official Catch. The stylesheet would have to be somehow optional of course.

**Comment by philsquared** [comment]
In reverse order:
* stylesheet reference: to what stylesheet?
* description & tags attributes - yes they probably should be added - I'll take a look - thanks

**Comment by mKlus** [comment]
RE: to what stylesheet?
To a user/developer provided stylesheet. One possibility could be adding a parameter to the command line so you can pass in a stylesheet to the xml reporter. Probably not best idea.
OR
Make it possible to extend xml reporter so I can just write the stylesheet reference to the xml in the extended reporter.

I've attached the style sheet I use to transform the xml into html. 
You can then just open the xml in browser (Chrome, IE...) and it will render as html.
The xml will have the below in the header. 

```
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="catch.xsl"?>
<Catch name="xyz">
...
```

[catch.zip](https://github.com/philsquared/Catch/files/759206/catch.zip)

**Comment by philsquared** [comment]
Ah right.
Yes making the XmlReporter extensible for that purpose sounds like a good way to go.

**Comment by philsquared** [comment]
I've merged (and simplified) and pushed the XML 1.0 changes now.
They should be in next patch release.

**Comment by philsquared** [comment]
[1.7.2](https://github.com/philsquared/Catch/releases/tag/v1.7.2) was released a few days ago with the stylesheet functionality in it. You just need to override `getStylesheetRef()` in a reporter derived from `XmlReporter` in addition to forwarding constructor, `getDescription()` and `INTERNAL_CATCH_REGISTER_REPORTER`.

It also moves back to Xml 1.0 and includes the description and tag attributes.
@mKlus can we consider this ticker resolved?

**Comment by mKlus** [comment]
Hi Phil, sorry... forgot to reply back on this...
1.7.2 works great. Thank for that!

Now we only need some sort of solution for 815 ;)
