### ISSUE TITLE
Question about context

### ISSUE THREAD

**Issue by FlYnN91** [philsquared/Catch#811]
## Description
Is there away to make each UNIT_TEST case within a *_test.cpp file _forget_ the context of already initialized variables?

Example:

```
uint16_t state = 0

/**
 * This test passes because init_module returns 1 - as expected.
 **/
UNIT_TEST("Test initialize","[test]")
{
    state = init_module();
    REQUIRE(state == 1);
}

/**
 * This test passes because the previous test sets state = 1, yet the state is initialized as 0.
 * If this test was positioned above the first test this test would fail, but I would expect this test to fail regardless of where it is positioned.
 **/
UNIT_TEST("Test state","[test]")
{
    REQUIRE(state == 1);
}
```

I know the command line switch to order tests in the random mode could help in getting around this problem and the UNIT_TEST -> SECTIONS implementation could be helpful. 

Any advice on how I could make the second test fail without going into trouble and writing _de_init_ functions in every *_test.cpp file?

**Comment by horenmar** [comment]
The only way to do exactly what you want requires running each test in a completely separate process, which Catch does not do.

The other solutions depend on why you are in this state and where do you want to end up. If the problem is that you have global dependencies in your test and want to ferret them out, then you should start running the test with random ordering of `TEST_CASE`s and when they fail, investigate whether there is some assumption about global state that does not hold.

If the problem is that you want some shared state that can be modified in different ways, then indeed `SECTION` macros are what you want:
```cpp
TEST_CASE("Test module"){
    uint16_t state = 0;
    SECTION("Initialization works") {
        state = init_module();
        REQUIRE(state == 1);
    }
    SECTION("Wrong state without init"){
        REQUIRE(state == 1); // This will fail
    }
}
```
because the paths taken through the test will be "Test module" -> "Initialization works" and "Test module" -> "Wrong state without init", but not "Test module" -> "Initialization works" -> "Wrong state without init".

**Comment by philsquared** [comment]
I think you should be able to do what you need by implementing a Listener (which is actually a specialised implementation of a reporter - gives you callbacks when a tests/ sections etc begin and end - so you can do your de-init in a test case end event?)
Unfortunately I've still not documented it, but you should be able to work it out from the issue thread I introduced it in: https://github.com/philsquared/Catch/issues/475

I'll try again to document it soon

**Comment by philsquared** [comment]
@FlYnN91 do either of these responses answer your question?

**Comment by FlYnN91** [comment]
@philsquared - yes, thank you.
