### ISSUE TITLE
Compilation failure on Windows

### ISSUE THREAD

**Issue by joto** [philsquared/Catch#819]
## Description
Version 1.7.1 fails to compile on Windows with error:

    error C3861: 'AddVectoredExceptionHandler': identifier not found
    error C3861: 'RemoveVectoredExceptionHandler': identifier not found

Looks like the same problem as #805, but this is not with Mingw, but MSVC.

You can see the build failure here: https://ci.appveyor.com/project/Mapbox/libosmium/build/job/fwvs2nol8mipx0j5

**Comment by philsquared** [comment]
I wonder if this is to do with this:

"To compile an application that uses this function, define the _WIN32_WINNT macro as 0x0500 or later. For more information, see Using the Windows Headers."
- https://msdn.microsoft.com/en-us/library/windows/desktop/ms679274(v=vs.85).aspx

**Comment by horenmar** [comment]
This is fairly interesting -- I looked at the build log from AppVeyor and the `WINVER`/`_WIN32_WINNT` macro is defined as `0x0500`, see `/D WINVER=0x0500 /D _WIN32_WINNT=0x0500`

Judging by a quick look at https://msdn.microsoft.com/en-us/library/windows/desktop/aa383745(v=vs.85).aspx#setting_winver_or__win32_winnt, this would indicate that you are building for pre-Windows XP version of Windows, which you obviously aren't, or at least shouldn't be. Now the question becomes WHY is it defined to that.

After looking at your build, I see that you are [adding these explicitly for some reason](https://github.com/osmcode/libosmium/blob/ab8236405330607932c8f6395956ec6d9bcdee5c/CMakeLists.txt#L210-L213). If you need to keep those, you can disable the SEH on Windows, [for details see our documentation](https://github.com/philsquared/Catch/blob/master/docs/configuration.md). Otherwise I recommend deleting these defines (they will be autodefined based on the OS version you build on), or bumping them up to at least `0x0502` (Windows XP SP 2).

**Comment by joto** [comment]
It is unclear to me why we added those windows version settings to the build script in the first place. I have removed them and now everything builds fine. Thanks for the help!
