### ISSUE TITLE
How to check code coverage by Catch Unit Tests?

### ISSUE THREAD

**Issue by hassanfarid** [philsquared/Catch#839]
## Description
This is more of a question, that how to check what section of code is not covered by Unit Tests?

**Comment by horenmar** [comment]
Your use-case is outside of scope for Catch, you will need a separate tool to check which lines were actually ran by your test suite.

One such tool is gcc's [`gcov`](https://gcc.gnu.org/onlinedocs/gcc/Gcov.html), but you will need to do some research for your specific platform.

**Comment by hassanfarid** [comment]
@ankit-shah2 - You can't do it with Catch framework.

**Comment by ankit-shah2** [comment]
@hassanfarid  Ok. Then how to proceed with it? Can we integrate some external tool and proceed (like gcov mentioned above)? Which? 
Also can you share tips on how to integrate.
I have already written UT's in catch and now I have been asked to get coverage percentage.

**Comment by Bu11etmagnet** [comment]
You need to build your unit tests with `--coverage`, run them, and then use gcov , or better yet, [lcov](http://ltp.sourceforge.net/coverage/lcov.php) to see which lines are being covered.

**Comment by horenmar** [comment]
Basically, collecting coverage needs either
* support from the compiler (gcov, llvm-cov, coverage-sanitizer), or
* hacky use of debugger (OpenCppCoverage).

Because Catch is a test framework, 1) is straight out (catch comes in after the compiler has already ran) and 2) would require us to create an out of process runner that understands platform specific debugger options.
