### ISSUE TITLE
Warning for parentheses around comparison in operand of ‘==’

### ISSUE THREAD

**Issue by barsan-ds** [philsquared/Catch#870]
I know this was reported many times and maybe fixed (at least for gcc 4.7) but I'm gaving this issue with GCC 6.3 on Linux Mint 18.

Anyway a temporary solution that works for me is to add
#pragma GCC diagnostic ignored "-Wparentheses"
in the source code

**Comment by horenmar** [comment]
We are currently attempting to suppress the warning by using `_Pragma` for GCC versions 4.8 and newer.

This would let us suppress it only for the assertion macros, but as it turns out, GCC likely has a long-standing bug in handling `_Pragma`s in C++ mode, as can be seen in this example

```cpp
#include <stdio.h>

#define TEST(expr) \
    int a = 1; \
    _Pragma( "GCC diagnostic push" ) \
    _Pragma( "GCC diagnostic ignored \"-Wparentheses\"" ) \
    if (a <= expr) { \
        printf("filler\n"); \
    } \
    _Pragma( "GCC diagnostic pop" )

int main(){
    int b = 2, c = 3;
    TEST(b == c);
}
```
If you compile this using current GCC as C, it will not trigger the warning. If you compile this as C++, it will warn about bad parentheses.


We will likely end-up using plain pragma to suppress the warning globally in the next release.

**Comment by onqtam** [comment]
I have the same experience in [doctest](https://github.com/onqtam/doctest) with ```_Pragma()``` not working for the g++ frontend - related bug reports:

- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55578
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69543

It's weird that I don't get the ```-Wparentheses``` warning though - but my expression decomposition uses ```operator<<``` (like [lest](https://github.com/martinmoene/lest) does) instead of ```operator<=```

**Comment by aldanor** [comment]
Same for me (GCC 5.2).

In my case, enabling `CATCH_CONFIG_FAST_COMPILE` (Catch v1.8.2) triggers a bajillion of `-Wparentheses` warnings that weren't there in the normal mode, and the build is in fact slower.

**Comment by aldanor** [comment]
Related: #565

**Comment by horenmar** [comment]
@aldanor Basically, at some point in the past (can't tell you version on top of my head, but a recent one), we switched to using `_Pragma`s for GCC that support them and only using `#pragma` for older ones. As it turns out, the `_Pragma` support in GCC is very spotty: I can compile a small Catch example file using g++-4.8 on my machine without warnings, but on different machine, with newer g++, the warnings come back. Also it has trouble with templates...


We will probably end up just using `#pragma` for all gcc versions and let it leak into the test files.

**Comment by horenmar** [comment]
I am going to close this, as I moved Catch back to force disabling `Wparentheses` everywhere using `#pragma` in 8f85d08e9f5bc0a1046d0f89e99d75fcbb453202.

This means that we disable the warning for GCC users even outside our assertions, but the spotty `_Pragma` support meant that the status quo was untenable.
