### ISSUE TITLE
Compilation error when private base of class of tested variable is "ostreamable" but class itself isn't

### ISSUE THREAD

**Issue by Predelnik** [philsquared/Catch#872]
## Description
When private base of class of tested variable is "ostreamable" but class itself isn't test code fails to compile.

### Steps to reproduce
```
#define CATCH_CONFIG_MAIN
#include <catch.hpp>
struct A {};
std::ostream &operator<< (std::ostream &o, const A &v) { return o << 0;}

struct B : private A
{
    bool operator==(int){ return true;}
};

B f ();
std::ostream g ();

TEST_CASE ("asdas")
{
    B x;
    REQUIRE (x == 4);
}

```

>main.cpp:1579:49: error: 'A' is an inaccessible base of 'B'
>         enum { value = sizeof( testStreamable(s << t) ) == sizeof( TrueType ) };

So the problem is in `IsStreamInsertable` check which features converting type to some bogus stremable type named `Borgtype` which everything converts to but it's pretty obvious that converting to your base class is still easier and thus error happens. It seems like replacing this check to the one featured in [this stackoverflow answer](http://stackoverflow.com/a/22759544/1269661) fixes this problem. I can send pull-request if that's needed and proposed solution is fine.

### Extra information
* Catch version: 1.8.2
* Operating System: Windows + online compilers
* Compiler+version: g++ 6.3.0, clang 3.8, MSVC 2017

**Comment by philsquared** [comment]
Thanks for bringing this up, @Predelnik. We haven't had an `IsStreamInsertable` issue for a while.
That SO answer is interesting. It can't be used as-is as it relies on (quite a few, actually) C++11 features - and Catch (1.x, at least) needs to keep working on pre-C++11 compilers.
But if the approach there is genuinely better we could do something conditionally (and would also be useful for Catch2 - which will assume C++11).
The "genuinely better" qualification is there because I know from looking at this before that every technique I investigated had one trade-off or another. That was a few years ago and I don't recall seeing anything like this one - so maybe it's better? But I'd like to see it more road tested before I switch it in by default (even for C++11 compilers) as if it has different trade-offs to the current approach then it will break currently working code.

So I think a starting point is to include it as an "opt-in" alternative.

If you're happy to put together a PR for that I'd be grateful. Otherwise I'll try and get to it myself in the near future (but not this week).
