### ISSUE TITLE
Test not failing when exception is thrown (in v1.9.0)

### ISSUE THREAD

**Issue by paulobrizolara** [philsquared/Catch#885]
## Description

I was doing some TDD with new Catch version (1.9.0).
When expecting that tests failed, they were passing.
Reducing the problem to minimum, discovered that the 
(expected) exception was been thrown. But the tests was passing.

I also tested with release 1.8.2 and it worked fine.

### Steps to reproduce

This minimal code can reproduce the error (i hope):

```c++
#define CATCH_CONFIG_MAIN
#include "catch.hpp"

TEST_CASE("should fail"){
    throw std::exception();
}
```

### Extra information

* Catch version: **v1.9.0**
* Operating System: **Linux**
* Compiler+version: **gcc 5.4.0**

**Comment by horenmar** [comment]
Well, that was an embarrassing mistake. The underlying cause was that to prevent double reporting of exceptions when using `CATCH_CONFIG_FAST_COMPILE`, unexpected exceptions had to be ignored under certain conditions. Due to a mistake on my part, when `CATCH_CONFIG_FAST_COMPILE` was not defined, all exceptions were ignored...

I am going to tag this with a revisit, because I need to take a look at why this didn't show up in Catch's self-test, but 1.9.1 is out and it should be fixed.

**Comment by horenmar** [comment]
I figured out why it didn't show up -- Phil approved the differences caused by the bug by mistake in 250f0ee7fbda0268cd91f2411236a923b44fbe39...

**Comment by philsquared** [comment]
Yup - sorry about that. Thought it was something else.
