### ISSUE TITLE
Let Approx::epsilon also take `float`

### ISSUE THREAD

**Issue by tomvierjahn** [philsquared/Catch#888]
## Description
* `Approx::Approx` and its comparison operators can now take  `float`
* Adding this feature to `Approx::epsilon` would improve consistency and code 

Somehow related to #873

### Extra information
* Catch version: **v1.9.1** (Generated: 2017-04-09 21:21:06.285364)

**Comment by horenmar** [comment]
I spent some time thinking about this, then suddenly got really busy and couldn't respond.


The reason why this wasn't a no-brainer change was that it isn't quite so simple as to add a `float` overload for the function, because that would trigger compile-time error for code like `Approx(2).margin(2)`. The solution that we are using is to add a templated overload, that uses SFINAE to only work with types that can be converted to double.

Now, for `Approx::margin` this isn't semantically problematic, as `Approx(temperature(72)).margin(temperature(2))`, makes perfect sense.  However for `Approx::epsilon` and the situation is not quite so clear-cut, as `Approx(temperature(72)).epsilon(temperature(0.001))` does not make semantical sense.

This could be solved in two ways.
1) Specifically make `Approx::epsilon` only accept floating point types (using `std::is_floating_point`).
2) Damn the semantics, make `Approx::epsilon` accept anything.
Personally I like the second option better.


*There is also `Approx::scale`, but I don't think anybody is actually using that one.*

**Comment by horenmar** [comment]
After discussion with Phil, I decided to go with option 2.
