### ISSUE TITLE
Doesn't execute test in function's section

### ISSUE THREAD

**Issue by faithandbrave** [philsquared/Catch#912]
## Description
- `TEST_CASE` calls function, and the function has `SECTION` and `REQUIRE` macros.
- Second call function doesn't execute test.
- If each function in `SECTION`, execute all tests.

### Steps to reproduce
```cpp
#define CATCH_CONFIG_MAIN
#include "catch.hpp"

void test_case(int a, int b)
{
    SECTION("my nested section") {
        if (a == 0) {
            REQUIRE(false);
        }
        else {
            REQUIRE(a == b);
        }
    }
}

TEST_CASE("my test case") {
    test_case(1, 1);
    test_case(0, 1);

    // workaround the bug
    //SECTION("a") { test_case(1, 1); }
    //SECTION("b") { test_case(0, 1); }
}
```

Output:

```
$ clang++ main.cpp
$ ./a.out
===============================================================================
All tests passed (1 assertion in 1 test case)
```

Should be:

```
my test case
  b
  my nested section
-------------------------------------------------------------------------------
main.cpp:6
...............................................................................

main.cpp:8: FAILED:
  REQUIRE( false )

===============================================================================
test cases: 1 | 1 failed
assertions: 2 | 1 passed | 1 failed
```

### Extra information
- Catch version : <https://github.com/philsquared/Catch/commit/b8443e67da47f02ec865ab38edc5756b1895b7e4>
    - use single header version
- Clang version : Apple LLVM version 8.0.0 (clang-800.0.42.1)

**Comment by horenmar** [comment]
At this moment this use case is not supported. Sections are meant to be ran only once and when the `test_case` function is called the second time, Catch sees that section called "my nested section" in file main.cpp at line 6 has already been executed under section (well, test_case) "my test case" and skips it.

Where it gets interesting is that even when I incorporate the function argument into the SECTION's name (`SECTION("nested section " + std::to_string(a)`), it won't be run again because tracker thinks that said section is already finished and does not need to be re-run. This might be changed, but the tracking logic is relatively complex and it will take me some time to trawl through it.

**Comment by faithandbrave** [comment]
Thank you for your information. The issue is not a bug.
