### ISSUE TITLE
Change to capture exception by (const) &

### ISSUE THREAD

**Issue by martinmoene** [philsquared/Catch#955]
Catch' `INTERNAL_CATCH_THROWS_AS()` catches its exception **by value**. The [Cpp Core Guidelines](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines) (Scott's More Effective C++ Item 13) advices to capture [exceptions by `(const) &`](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Re-exception-ref).

See [`catch_capture.hpp`](https://github.com/philsquared/Catch/blob/fae0fa4ec158438b9f6c6f8b4d73bdf631c08ed6/include/internal/catch_capture.hpp#L133) line 133.

Noted [here at doctest](https://github.com/onqtam/doctest/issues/81).

**Comment by philsquared** [comment]
This changed at some point. I think there was some complaint that by doing it by reference within the macro you didn't get the opportunity to choose different approaches yourself.
With it not being in the macro you can still add the reference to the type you pass as the argument to the macro.

I'm still not sure how I feel about this one.

I'm inclined to change it back, but that would now be a breaking change (especially if you've added the reference externally). So I may revisit for Catch2.

**Comment by horenmar** [comment]
We catch by whatever type we are given, user can choose to have Catch capture by `const&` just by writing it that way.

We actually had it using TMP to ensure the type is properly `const&`-ed no matter what, but that broke people who used the macros inside a templated function, and couldn't be fixed in C++98 (IIRC it was because `typename` cannot be used in plain old function and without it, it didn't work in templated functions).

This rule was changed in C++11, so we can do it without breaking people who used it correctly, but that would mean using type traits in the common include path, which is... unfortunate.

**Comment by martinmoene** [comment]
Tes it is: [Expects that an exception of the specified type is thrown during evaluation of the expression. Note that the exception type is used verbatim and you should include (const) reference.](https://github.com/philsquared/Catch/blob/master/docs/assertions.md#exceptions).

**Comment by philsquared** [comment]
Yeah. Could be clearer, though.
Personally I would be happy to just unconditionally add the `const&` - and provide an alternate way (or let user do it the long way round) for cases where that was not wanted (which must be a small edge case).
As I say, though, that would be quite a breaking change - so will think about it for Catch2.

**Comment by martinmoene** [comment]
Thanks for the feedback.

**Comment by philsquared** [comment]
Thanks for bringing this up, @martinmoene

**Comment by horenmar** [comment]
Since most people seem to use this wrong, I've decided to change this for Catch 2.
