### ISSUE TITLE
Private implicit conversion operator causes catch compiler failure

### ISSUE THREAD

**Issue by bdb** [philsquared/Catch#956]
We have a class similar to the following:

```
class AClass {
    int val;
    template<typename T>
    operator T() const;

public:
    AClass():val(1){}

    int value() const {
        return val;
    }
    operator bool() const {
        return 0 == val;
    }
};
```

We do this for backward compatibility with a C++98 code base (where explicit is not available).

Using catch 1.9.3 and Xcode 8.3.3. and GCC 5.4 on Linux this worked in C++14 mode. I just upgraded to catch 1.9.6 and now both compilers are failing with similar errors:

'operator << is ambiguous for AClass' on line 1606 of the 1.9.6 header in testStreamable()

I was able to workaround it by adding C++ version checks to use explicit when possible, but this kind of pattern is valid C++ code and should not cause issues with Catch.

**Comment by horenmar** [comment]
I assume you are doing something like this
```cpp
AClass ac;
REQUIRE(ac);
```

this fails, because at some point between 1.9.3 and 1.9.6 we changed how truthy expressions are stringified. Now, instead of printing "true" or "false", depending on what the truthy expression evaluated to, the expression is stringified as normal. 

This causes error because Catch checks whether your class can be streamed to `std::ostream`, and during this check, the implicit conversion operator is found and overload resolution explodes. There is however an easy solution: provide properly matching overload of `operator<<`.

```cpp
std::ostream& operator<<(std::ostream& out, AClass) {
    // This can be left empty if you don't care
    return out;
}
```

**Comment by philsquared** [comment]
... or to get back the previous behaviour (less useful, but for completeness), do:

```c++
AClass ac;
REQUIRE(!!ac);
```

**Comment by horenmar** [comment]
I assume you are doing something like this
```cpp
AClass ac;
REQUIRE(ac);
```

this fails, because at some point between 1.9.3 and 1.9.6 we changed how truthy expressions are stringified. Now, instead of printing "true" or "false", depending on what the truthy expression evaluated to, the expression is stringified as normal. 

This causes error because Catch checks whether your class can be streamed to `std::ostream`, and during this check, the implicit conversion operator is found and overload resolution explodes. There is however an easy solution: provide properly matching overload of `operator<<`.

```cpp
std::ostream& operator<<(std::ostream& out, AClass) {
    // This can be left empty if you don't care
    return out;
}
```
