### ISSUE TITLE
Static analysis results of Catch-2

### ISSUE THREAD

**Issue by martinmoene** [philsquared/Catch#958]
[martinmoene/Catch-2 Static Analysis](https://gist.github.com/martinmoene/e08fa06258318e1f834840486afa294e).

Contains 

- [PVS-Studio](https://gist.github.com/martinmoene/e08fa06258318e1f834840486afa294e#file-pvs-studio-txt)
- [Resharper-C++](https://gist.github.com/martinmoene/e08fa06258318e1f834840486afa294e#file-resharper-c-txt)
- [VC-CppCoreCheck-released.txt](https://gist.github.com/martinmoene/e08fa06258318e1f834840486afa294e#file-vc-cppcorecheck-released-txt)

**Comment by horenmar** [comment]
Went through PVS-Studio:


```
V690 The '=' operator is declared as private in the 'MatcherUntypedBase' class, but the default copy constructor will still be generated by compiler. It is dangerous to use such a class. SelfTest catch_matchers.hpp 23
V690 The 'ExpressionLhs' class implements the '=' operator, but lacks a copy constructor. It is dangerous to use such a class. SelfTest catch_expression_lhs.hpp 26
V690 The 'BinaryExpression' class implements the '=' operator, but lacks a copy constructor. It is dangerous to use such a class. SelfTest catch_expression_lhs.hpp 105
```

This is intentional, copy assignment is disabled and the default copy constructor works properly. Hopefully explicitly deleting `operator=` and defaulting the copy constructor makes this go away.


```
V690 The '=' operator is declared as private in the 'AssertionPrinter' class, but the default copy constructor will still be generated by compiler. It is dangerous to use such a class. SelfTest catch_reporter_compact.cpp 70
V690 The '=' operator is declared as private in the 'AssertionPrinter' class, but the default copy constructor will still be generated by compiler. It is dangerous to use such a class. SelfTest catch_reporter_console.cpp 99
V690 The '=' operator is declared as private in the 'AssertionPrinter' class, but the default copy constructor will still be generated by compiler. It is dangerous to use such a class. SelfTest catch_reporter_tap.hpp 63
```
I ended up explicitly forbidding both, there is no reason to copy construct it either.

```
V690 The 'Colour' class implements a copy constructor, but lacks the '=' operator. It is dangerous to use such a class. SelfTest catch_console_colour.hpp 15
```
Since this is a scope guard kinda class, I deleted copy constructor and implemented move constructor/assignment instead (interestingly, they aren't used anywhere anyway).

```
V690 The 'ScopedMessage' class implements a copy constructor, but lacks the '=' operator. It is dangerous to use such a class. SelfTest catch_message.h 49
```
Deleted explicit copy constructor, the compiler generated one works fine.

```
V524 It is odd that the body of 'compare' function is fully equivalent to the body of 'applyEvaluator' function. SelfTest catch_evaluate.hpp 98
```
Going to pass this one over, the entire evaluator layer is bit of a mess.

```
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: macroName, capturedExpression, resultDisposition. SelfTest catch_assertionresult.h 43
```
I think this is some weird false positive, macroName defaults to nullptr and the default constructor should initialize it that way. The exception is resultDisposition, which should now be properly initialized in the default constructor. Non default constructor also looks correct.

```
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: m_mode, m_exclusion, m_start, m_pos. SelfTest catch_test_spec_parser.hpp 33
```
These now have default values.

```
V690 The 'ScopedElement' class implements a copy constructor, but lacks the '=' operator. It is dangerous to use such a class. SelfTest catch_xmlwriter.hpp 83
```
Again, scope guard kinda class, implemented both moves and removed copy constructor.

```
V690 The 'NotImplementedException' class implements a copy constructor, but lacks the '=' operator. It is dangerous to use such a class. SelfTest catch_notimplemented_exception.h 15
```
Deleted explicit copy constructor, the compiler generated one works fine.

```
V690 The '=' operator is declared as private in the 'Version' class, but the default copy constructor will still be generated by compiler. It is dangerous to use such a class. SelfTest catch_version.h 16
```
I ended up explicitly deleting both copy operations, there is no reason to copy version around.

```
V667 The 'throw' operator does not possess any arguments and is not situated within the 'catch' block. SelfTest catch_exception_translator_registry.cpp 59
```
This will have to be explicitly disabled as FP.


V565 An empty exception handler. Silent suppression of exceptions can hide the presence of bugs in source code during testing. SelfTest catch_run_context.cpp 238
This is also likely going to end up explicitly disabled as FP.

```
???? V601 The result of '-' operator is implicitly cast to the bool type. Inspect the second argument. SelfTest catch_reporter_junit.cpp 109
```
I have absolutely no idea what this one is trying to say.

**Comment by martinmoene** [comment]
Thanks for the extensive report(s).

>???? V601 The result of '-' operator is implicitly cast to the bool type. Inspect the second argument. SelfTest catch_reporter_junit.cpp 109

I gazed at this for some time; it seems to be produced by some deep thought, but in the end is double Dutch even to me, hence the `???`.

**Comment by martinmoene** [comment]
@horenmar I've updated the results for [PVS-Studio](https://gist.github.com/martinmoene/e08fa06258318e1f834840486afa294e#file-pvs-studio-txt) and [Resharper-C++](https://gist.github.com/martinmoene/e08fa06258318e1f834840486afa294e#file-resharper-c-txt) (now 91 lines).

**Comment by horenmar** [comment]
@martinmoene 
Are you using latest PVS Studio? Because if so, this might actually be worth reporting as a bug:
```
V690 The 'Colour' class implements the '=' operator, but lacks a copy constructor. It is dangerous to use such a class. SelfTest catch_console_colour.hpp 15
V690 The 'ScopedElement' class implements the '=' operator, but lacks a copy constructor. It is dangerous to use such a class. SelfTest catch_xmlwriter.hpp 37
```
Colour implements *move* assignment operator and *move* constructor. This disables autogeneration of copy operations and thus this is completely bogus. It also might not be a bug, just limitation of their parser, because these 2 are also fun and proper code model should not hit them:
```
V803 Decreased performance. In case 'm_refs' is iterator it's more effective to use prefix form of increment. Replace iterator++ with ++iterator. SelfTest catch_stringdata.h 33
V803 Decreased performance. In case 'm_refs' is iterator it's more effective to use prefix form of decrement. Replace iterator-- with --iterator. SelfTest catch_stringdata.h 38
```
(they are atomic unsigned ints).

Anyway, I think I addressed those that are part of Catch (not Clara) and aren't just a FP. I don't want to start marking up Catch's code with suppressions for all different static analyzers just yet.


To not be completely down on PVS, I actually liked some of the warnings like V820 (variable is unused after being copied, consider move), it just goes dumb bit too much for my liking.

**Comment by martinmoene** [comment]
> `virtual void foo() override`

+1

**Comment by martinmoene** [comment]
@horenmar, ref. [comment above](https://github.com/philsquared/Catch/issues/958#issuecomment-317742331)

I was using the latest version, PVS Studio 6.16 and I've contacted viva64 with approximately the following message (safe cordiality):

>PVS Studio 6.16 unexpectedly reports V690, lack of copy constructor, on a move-only type. It appears to interpret the move-assignment operator as a copy-assignment operator.
>
>Could this be a bug or is it a limitation of the tool?
```
struct move_only 
{
    move_only();
    move_only( move_only&& other );
    move_only& operator=( move_only&& other );
    ~move_only();

    bool f = false;
};
```
>V690 The 'move_only' class implements the '=' operator, but lacks a copy constructor.

**Comment by martinmoene** [comment]
viva64 recognises above as a false positive and they'll investigate it and try to fix it.

**Comment by horenmar** [comment]
I went through the VC cppcorecheck briefly, but I don't think it is quite ready for production yet:

```
reporters\catch_reporter_junit.cpp(26): warning C26496: Variable 'timeStampSize' is assigned only once, mark it as const. 
reporters\catch_reporter_bases.cpp(28): warning C26496: Variable 'maxDoubleSize' is assigned only once, mark it as const. 
```
the referred to places:
```
const size_t timeStampSize = sizeof("2017-01-16T17:06:45Z");
const size_t maxDoubleSize = DBL_MAX_10_EXP + 1 + 1 + 3 + 1;
```

Some of the other reports are obviously true (Catch codebase isn't exactly const-nazi about variables in functions), but this doesn't fill me with great confidence.

Some of the reports I couldn't find at all:
```
reporters\catch_reporter_compact.cpp(39): warning C26493: Don't use C-style casts that would perform a static_cast downcast, const_cast, or reinterpret_cast. 
reporters\catch_reporter_console.cpp(38): warning C26493: Don't use C-style casts that would perform a static_cast downcast, const_cast, or reinterpret_cast. 
... many others I tried
```

And even when it isn't wrong, some of the messages are downright cryptic:
```
reporters\catch_reporter_bases.cpp(38): warning C26485: Expression 'buffer': No array to pointer decay.
...
```


All in all, I am going to ignore cppcorecheck reports and close this issue.
