### ISSUE TITLE
clang-tidy complains about a catch handler catching a pointer value

### ISSUE THREAD

**Issue by dawagner** [philsquared/Catch#968]
## Description
When analysing tests using the `CHECK_THROWS_AS` or `REQUIRE_THROWS_AS` macros, clang-tidy reports "catch handler catches a pointer value; should throw a non-pointer value and catch by reference instead [cert-err61-cpp]".

### Steps to reproduce
Minimum reproduction code: 

```
#include "catch.hpp"
#include <vector>
#include <stdexcept>

TEST_CASE("foo")
{
  std::vector<int> vec;
  CHECK_THROWS_AS(vec.at(42), std::out_of_range);
}
```

### Extra information
I tried adding "nolint" comments to some place I believed were relevant but to no avail.

* Catch version: **v1.9.6**
* Operating System: **Fedora 25**
* Compiler+version: **clang-tidy 3.9.0**

**Comment by horenmar** [comment]
I am fairly sure you have wrong Catch version there 😉 

Anyway, the underlying reason is that Catch 1 uses specified type verbatim, so to catch by `const&` you have to specify exception type with `const&`, like so
```cpp
#include "catch.hpp"
#include <vector>
#include <stdexcept>

TEST_CASE("foo") {
  std::vector<int> vec;
  CHECK_THROWS_AS(vec.at(42), std::out_of_range const&);
}
```

In Catch 2, we will be adding the `const&` unconditionally, because it seems to be catching many people off-guard. See #955 for details.

**Comment by dawagner** [comment]
Right, there was a "4" leftover in the version number from the template :)

Thank you for the explanation.
