### ISSUE TITLE
[Overarching] Approx issues

### ISSUE THREAD

**Issue by horenmar** [philsquared/Catch#980]
There are multiple currently open issues against Approx, that need fixing. Because floating point is hard, it will take a while to fix them properly. In the meantime, this is an overarching issue to keep track of the progress.

### Related issues
* #952 - Margin is non-inclusive (and does not quite work properly)
* #953, #962 - Default approx scale leads to weird results for small numbers

**Comment by TBBle** [comment]
For the record, [cppreference](http://en.cppreference.com/w/cpp/types/numeric_limits/epsilon) gives a reasonable example of floating-point comparison with a relative precision.
```cpp
template<class T>
typename std::enable_if<!std::numeric_limits<T>::is_integer, bool>::type
    almost_equal(T x, T y, int ulp)
{
    // the machine epsilon has to be scaled to the magnitude of the values used
    // and multiplied by the desired precision in ULPs (units in the last place)
    return std::abs(x-y) < std::numeric_limits<T>::epsilon() * std::abs(x+y) * ulp
    // unless the result is subnormal
           || std::abs(x-y) < std::numeric_limits<T>::min();
}
```

The current API documentation is quite confusing, it's not clear if `episilon` is a percentage with an amazingly low default, or is a value from which a percentage is derived through _magic_, since the docs don't show any relationship between the value set, and the percentage.

`margin` itself is clear, except as noted in #952 the documentation implies it's an inclusive range for success, but the code itself is exclusive range for success.

I don't see why you'd want `scale` distinctly, but it might be due to confusion over `epsilon`'s behaviour, per #962. (The code confused me _further_...)

I also can't see how or why you'd want to combine _both_ relative and absolute tolerances, but I can't really give a reason that you wouldn't.

So it would make sense for me (and avoid surprising existing satisfied users) to introduce two new things like `Approx`:
* `input == Within(value, inclusiveAbsoluteRangeValue)` implying `fabs(input-value) <= inclusiveAbsoluteRangeValue `; and
* `input == Roughly(value, someRelativeMeasure)` implying `fabs(input-value) <= fabs(input-value) * std::numeric_limits<decltype(input-value)>::epsilon() * mutationOf(someRelativeMeasure)`.

That second `fabs(input-value)` might be the wrong multiplier for `std::numeric_limits<>::epsilon`, I see Catch currently takes the machine epsilon of the max of the two sides, rather than the machine epsilon of the difference.

It seems to me that `Within(x, 0)` would be the same as `Rougly(x,0)` and also would do what `==` does if you ignore the floating-point-equality-comparison warnings. So I'd further propose that be what `Roughly(x)` does, as that was another surprise we got from `Approx`, the described defaults seem more lenient than expected.

That mainly leaves the definition of `mutation` open. I don't have any suggestion for expressing relative difference. ULPs (per cppreference above) has the right behaviour for precisely-equal (via the subnormal check) however I don't understand them clearly enough in a mathematical sense to say it's actually correct.

**Comment by NoLongerBreathedIn** [comment]
Also a good idea: allowing INFINITY == Approx(INFINITY).
Currently this is false.

**Comment by horenmar** [comment]
The three issues that initially prompted making this issue will be fixed in Catch 2, by making default `scale` 0 and making `epsilon` only apply to `Approx`'s value, rather than to larger of the two values (which is computationally correct, but misleading when used in class context).

I also fixed `INFINITY == Approx(INFINITY)` by changing how margins are compared.


We are planning to provide an ULP-based matcher at some point, but that is still in the future.

**Comment by martinmoene** [comment]
Perhaps there's useful info at [stf](https://github.com/jfalcou/stf) - Simple TDD Framework. Catch/lest-inspired with an emphasis on floating point precision testing.
