### ISSUE TITLE
inconsistent and surprising behaviour of CHECK(size_t(-1) == -1)

### ISSUE THREAD

**Issue by egonk** [philsquared/Catch#981]
## Description

``CHECK(size_t(-1) == -1)`` is interpreted inconsistently on VS2015 vs g++ and clang. The behaviour should probably match the compiler (pass for both cases or fail for both)...?

VS2015 win32: OK
VS2015 x64: OK
Linux g++ 4.8.2 x64: FAIL
Mac clang (?) x64: FAIL

### Steps to reproduce
```
TEST_CASE("size_t")
{
	INFO("sizeof(int)" << sizeof(int));
	INFO("sizeof(size_t)" << sizeof(size_t));
	CHECK(bool(size_t(-1) == -1));
	CHECK(size_t(-1) == -1); // problem
}
```

### Extra information
* Catch version: **1.9.6**

VS2015 x64:
```
-------------------------------------------------------------------------------
size_t
-------------------------------------------------------------------------------
x.cpp(678)
...............................................................................

x.cpp(682):
PASSED:
  CHECK( bool(size_t(-1) == -1) )
with expansion:
  true
with messages:
  sizeof(int)4
  sizeof(size_t)8

x.cpp(683):
PASSED:
  CHECK( size_t(-1) == -1 )
with expansion:
  18446744073709551615 == -1
with messages:
  sizeof(int)4
  sizeof(size_t)8
```

Linux g++ 4.8.2 x64:
```
-------------------------------------------------------------------------------
size_t
-------------------------------------------------------------------------------
x.cpp:678
...............................................................................

x.cpp:682: 
PASSED:
  CHECK( bool(size_t(-1) == -1) )
with expansion:
  true
with messages:
  sizeof(int)4
  sizeof(size_t)8

x.cpp:683: FAILED:
  CHECK( size_t(-1) == -1 )
with expansion:
  18446744073709551615 (0xffffffffffffffff)
  ==
  -1
with messages:
  sizeof(int)4
  sizeof(size_t)8
```

**Comment by philsquared** [comment]
That's very interesting.
It looks like this issue has been in the code since at least the early days of Catch - if not the start.
Ironically, you have surfaced it over six years later - and just a few days after I overhauled the relevant code in the Catch2 (`dev-modernise`) branch *which no longer has the issue*!

I've merged the commit back that actually fixes it - but as it's a fairly impactful change I've put it on a branch off master for now: `reevaluate-merge`. I've generated the single include on that branch. Could you please try this file:

https://raw.githubusercontent.com/philsquared/Catch/reevaluate-merge/single_include/catch.hpp

... and confirm that your issue has gone away (I've verified it on clang on macOs).
Then we'll consider whether to commit that back to the main branch.

FYI the issue was todo with the way Catch captures integers as template arguments. In Catch 1.x it has a set of heuristic-based overloads to avoid getting signed/ unsigned mismatches due to how integer literals are deduced in isolation. I've now removed that in favour of just suppressing the warnings!

Thanks!

**Comment by philsquared** [comment]
(sorry - didn't mean to close - wrong button!)

**Comment by egonk** [comment]
I've tested it on VS2015 x64 and Linux g++ 4.8.2 x64 and it works on both. Thanks a lot!

**Comment by philsquared** [comment]
Thanks for reporting back. Now considering whether to merge that onto master (Catch2 should not have this issue)

**Comment by horenmar** [comment]
The evaluate change is part of the latest release, so I am going to close this issue.

**Comment by vadz** [comment]
This broke support for MSVC 9 (a.k.a. MSVS 2008) and probably other older compilers, see e.g. https://stackoverflow.com/questions/46477686/errors-when-compiling-catch-with-visual-studio-2008

**Comment by horenmar** [comment]
This is why we can't have nice things

**Comment by vadz** [comment]
Well, we can, in Catch2... but for Catch1 I think it would really make sense to revert b6e7c9bd7a160c07c5de894292022687895c17a3 (done on top of the older commit) and b7bd52cc98f8a9b646a13241ce8355ba97b8bab3 itself to keep it working with the old compilers it is meant for.
