### ISSUE TITLE
Documentation for GENERATE macro and generators?

### ISSUE THREAD

**Issue by RossBencina** [philsquared/Catch#988]
## Description

Catch appears to support test data generation via the `GENERATE` macro. See the examples here:

https://github.com/philsquared/Catch/blob/master/projects/SelfTest/GeneratorTests.cpp

I have been unable to locate any documentation that references `GENERATE` or the other syntax used in `GeneratorTests.cpp`

### Steps to reproduce

Search for `GENERATE` on the documentation pages.

### Questions

* Does the documentation exist?
* Is `GENERATE` a supported feature? I have found it useful on the few occasions that I've used it.
* Are there more examples somewhere?
* Could we at least add a stub documentation page to reference the feature?

**Comment by philsquared** [comment]
Hi @RossBencina,

1. Documentation does not exist. This is deliberate because...
2. ... This is not a supported feature. It was originally experimental - but hit some systemic issues that caused a rethink (and some preparatory rework). There's a new implementation off to the side (not in GitHub) that works properly, but is not finished. This will be going into Catch2.
3. No (not for this implementation)
4. You raise a good point, indirectly, that the lack of documentation does not adequately convey the unsupported nature.

The original implementation went in quite early on and got stuck there. I know some people have used it, so I didn't want to take it out. The main problem with it (apart from being incomplete) is it doesn't work with sections.

**Comment by philsquared** [comment]
I'm going to close this issue as the future facing aspect is covered by https://github.com/philsquared/Catch/issues/850.

But let me know if you have any more questions, @RossBencina
