### ISSUE TITLE
CATCH_PLATFORM_WINDOWS not defined when CATCH_CONFIG_FAST_COMPILE=1

### ISSUE THREAD

**Issue by Trass3r** [philsquared/Catch#994]
Tested the v2.0.0-develop.2 prerelease.

```
#define CATCH_CONFIG_MAIN
#define CATCH_CONFIG_FAST_COMPILE
//#define CATCH_CONFIG_WINDOWS_CRTDBG
#include "catch.hpp"

TEST_CASE("a", "")
{
	new int[1000];
}
```

fails with `catch.hpp(5267): error C3646: 'oldSigStack': unknown override specifier`
because CATCH_PLATFORM_WINDOWS is not defined.
CATCH_BREAK_INTO_DEBUGGER is not defined either.

**Comment by horenmar** [comment]
Our stitching script strikes again! For some background, if `CATCH_CONFIG_FAST_COMPILE` is defined, quite a lot of code is `ifdef`ed away from the file, including all of `CATCH_PLATFORM_*`.

The problem is, that each Catch header is stitched-in only once, so when later code depends on the `catch_platform.h` include, it is still ifdefed away.

This should be easy enough to fix though.

**Comment by horenmar** [comment]
We did some restructuring of how includes and stitching work, so this shouldn't happen again.
